Repository magpiemodel/magpie, pull requests merged in 2021-11, with the labels that each got.

#338 removed time dimension from regional maximum afforestation input
  config/default.cfg
  modules/32_forestry/dynamic_feb21/input.gms
  modules/32_forestry/dynamic_feb21/preloop.gms
  scripts/output/extra/highres.R
Labels: Minor, Low risk

#344 bugfix disaggregation.R output script
  scripts/output/extra/disaggregation.R
Labels: bug, Minor, Low risk

#343 Update of water demand realization and dairy fade out
  CHANGELOG.md
  config/default.cfg
  main.gms
Labels: High risk, Release candidate

#345 bugfix: urban land
  config/default.cfg
  modules/34_urban/exo_nov21/presolve.gms
Labels: Minor, High risk, bugfix

#346 update cfg to rev4.65
  CHANGELOG.md
  config/default.cfg
Labels: Low risk

#347 script for adding snapshots to .Rprofile file
  CHANGELOG.md
  config/default.cfg
  scripts/output/extra/highres.R
  scripts/start/Rprofile.R
Labels: enhancement, Minor, Low risk, Release candidate

#348 Update scenario_config rev4.65 + highres output script
  config/scenario_config.csv
  scripts/output/extra/highres.R
  scripts/start/projects/project_LAMACLIMA_WP4.R
Labels: Minor, Low risk, Release candidate, bugfix
