Repository magpiemodel/magpie, pull requests merged in 2021-05, with the labels that each got.

#275 Develop
  .zenodo.json
  CHANGELOG.md
  CITATION.cff
  README.md
  config/default.cfg
  main.gms
  modules/15_food/anthropometrics_jan18/intersolve.gms
  modules/18_residues/flexreg_apr16/declarations.gms
  modules/18_residues/flexreg_apr16/postsolve.gms
  modules/44_biodiversity/bv_btc_mar21/declarations.gms
  modules/51_nitrogen/ipcc2006_sep16/declarations.gms
  modules/51_nitrogen/ipcc2006_sep16/postsolve.gms
  modules/51_nitrogen/rescaled_jan21/declarations.gms
  modules/51_nitrogen/rescaled_jan21/postsolve.gms
  scripts/start/projects/paper_scp.R
Labels: Low risk, Minor

#277 nocc2020 switch added
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  core/declarations.gms
  core/sets.gms
  modules/14_yields/biocorrect/input.gms
  modules/14_yields/dynamic_aug18/input.gms
  modules/42_water_demand/agr_sector_aug13/input.gms
  modules/42_water_demand/all_sectors_aug13/input.gms
  modules/43_water_availability/total_water_aug13/input.gms
  modules/52_carbon/normal_dec17/input.gms
  modules/52_carbon/off/input.gms
  modules/59_som/cellpool_aug16/equations.gms
  modules/59_som/cellpool_aug16/input.gms
  modules/59_som/static_jan19/input.gms
Labels: Low risk, Minor

#279 Bug fix of sm_fix_SSP2 and sm_fix_cc declaration
  CHANGELOG.md
  config/default.cfg
  core/declarations.gms
  modules/09_drivers/aug17/declarations.gms
Labels: Low risk, Minor, bug

#276 Ignore historic TAU patterns + land conversion costs forestry + Bugfix BII + Bugfix NPI/NDC afforestation
  CHANGELOG.md
  config/default.cfg
  core/sets.gms
  modules/13_tc/endo_jun18/input.gms
  modules/13_tc/endo_jun18/presolve.gms
  modules/32_forestry/dynamic_feb21/declarations.gms
  modules/32_forestry/dynamic_feb21/equations.gms
  modules/32_forestry/dynamic_feb21/input.gms
  modules/32_forestry/dynamic_feb21/preloop.gms
  modules/32_forestry/dynamic_feb21/presolve.gms
  modules/35_natveg/dynamic_feb21/equations.gms
  modules/39_landconversion/global_static_aug18/input.gms
  modules/39_landconversion/global_static_aug18/preloop.gms
  modules/39_landconversion/global_static_aug18/realization.gms
  modules/44_biodiversity/bv_btc_mar21/sets.gms
  scripts/start/projects/TAUhistfree.R
  scripts/start/projects/forestry.R
  scripts/start/projects/forestry_co2.R
  scripts/start/projects/project_vivid.R
  scripts/start/test_runs.R
Labels: High risk, Minor, bug, enhancement

#278 CH4 and NH3 emissions from the burning of agricultural residues
  CHANGELOG.md
  config/default.cfg
  modules/53_methane/ipcc2006_flexreg_apr16/declarations.gms
  modules/53_methane/ipcc2006_flexreg_apr16/equations.gms
  modules/53_methane/ipcc2006_flexreg_apr16/input.gms
  modules/53_methane/ipcc2006_flexreg_apr16/preloop.gms
  modules/53_methane/ipcc2006_flexreg_apr16/realization.gms
  modules/53_methane/ipcc2006_flexreg_apr16/sets.gms
  modules/53_methane/module.gms
  modules/53_methane/off/not_used.txt
  modules/53_methane/off/realization.gms
Labels: High risk, Minor, enhancement, good first issue
