Repository magpiemodel/magpie, pull requests merged in 2021-07, with the labels that each got.

#286 bugfix missing plantation area
  CHANGELOG.md
  config/default.cfg
  modules/32_forestry/dynamic_feb21/preloop.gms
  modules/35_natveg/dynamic_feb21/input.gms
Labels: bugfix

#287 update scenario config. Added RCP scenarios for use with setScenario
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  scripts/start/extra/lpjml_addon.R
Labels: Low risk, enhancement

#285 bugfix croparea correction
  modules/14_yields/managementcalib_aug19/declarations.gms
  modules/14_yields/managementcalib_aug19/preloop.gms
  modules/30_crop/endo_apr21/preloop.gms
  modules/30_crop/endo_jun13/preloop.gms
  scripts/start/extra/lpjml_addon.R
Labels: Medium risk, bug

#291 Hf update lpjmladdon
  scripts/start/extra/lpjml_addon.R
Labels: Low risk, Minor

#292 Hotfix sticky and managementcalib with new dual layer
  modules/14_yields/managementcalib_aug19/preloop.gms
  modules/38_factor_costs/sticky_feb18/presolve.gms
Labels: Low risk, Minor, bugfix
