Repository magpiemodel/magpie, pull requests merged in 2021-12, with the labels that each got.

#349 bioenergy yield input data bugfix + smaller updates
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  core/sets.gms
  main.gms
  modules/32_forestry/dynamic_feb21/preloop.gms
  modules/35_natveg/dynamic_feb21/preloop.gms
  modules/35_natveg/dynamic_feb21/presolve.gms
  modules/60_bioenergy/1stgen_priced_dec18/input.gms
  modules/60_bioenergy/1stgen_priced_dec18/presolve.gms
  modules/70_livestock/fbask_jan16/preloop.gms
  output.R
  scripts/calibration/landconversion_cost.R
  scripts/output/extra/disaggregation_LUH2.R
  scripts/output/extra/highres.R
  scripts/run_submit/submit_standby_maxMem.sh
  scripts/start/Rprofile.R
  scripts/start/projects/project_LAMACLIMA_WP4.R
Labels: Minor, High risk, Release candidate, bugfix

#350 Add new option to take ghg prices from different file than the regular reporting file in coupling, clean parameter list of start_run()
  CHANGELOG.md
  config/default.cfg
  modules/56_ghg_policy/price_jan20/preloop.gms
  modules/60_bioenergy/1stgen_priced_dec18/preloop.gms
  modules/60_bioenergy/1stgen_priced_dec18/presolve.gms
  scripts/start_functions.R
Labels: Minor, Low risk, Release candidate

#352 Update start script test runs + Bugfix
  CHANGELOG.md
  config/default.cfg
  modules/60_bioenergy/1stgen_priced_dec18/preloop.gms
  scripts/start/test_runs.R
  scripts/start/test_runs2.R
Labels: enhancement, Minor, Release candidate, bugfix

#353 start and output scripts
  scripts/output/extra/disaggregation_LUH2.R
  scripts/start/projects/project_BEST.R
  scripts/start/projects/project_LAMACLIMA_WP4.R
Labels: enhancement, Minor, Low risk, Release candidate, bugfix
