Repository magpiemodel/magpie, pull requests merged in 2021-08, with the labels that each got.

#304 Bug fix in the variable costs of sticky
  CHANGELOG.md
  modules/38_factor_costs/sticky_feb18/declarations.gms
  modules/38_factor_costs/sticky_feb18/equations.gms
  modules/38_factor_costs/sticky_feb18/input.gms
  modules/38_factor_costs/sticky_feb18/postsolve.gms
  modules/38_factor_costs/sticky_feb18/presolve.gms
  scripts/start/projects/sticky.R
Labels: Low risk, bugfix

#305 Update of maximum cropland land conversion cost
  modules/39_landconversion/devstate/input.gms
  scripts/start/extra/lpjml_addon.R
Labels: Minor, Low risk

#288 Addition of depreciation rate in irrigation area expansion (41_area_equipped_for_irrigation)
  CHANGELOG.md
  config/default.cfg
  main.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/equations.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/postsolve.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/presolve.gms
  scripts/start/irrig_dep_test.R
Labels: enhancement, Medium risk
