Repository magpiemodel/magpie, pull requests merged in 2021-09, with the labels that each got.

#310 Develop
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  core/sets.gms
  main.gms
  modules/14_yields/biocorrect/input.gms
  modules/14_yields/dynamic_aug18/input.gms
  modules/14_yields/managementcalib_aug19/input.gms
  modules/32_forestry/dynamic_feb21/input.gms
  modules/38_factor_costs/sticky_feb18/input.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
  modules/41_area_equipped_for_irrigation/static/input.gms
  modules/42_water_demand/agr_sector_aug13/input.gms
  modules/42_water_demand/all_sectors_aug13/input.gms
  modules/43_water_availability/total_water_aug13/input.gms
  modules/51_nitrogen/input/files
  modules/51_nitrogen/ipcc2006_sep16/declarations.gms
  modules/51_nitrogen/ipcc2006_sep16/equations.gms
  modules/51_nitrogen/ipcc2006_sep16/input.gms
  modules/51_nitrogen/ipcc2006_sep16/input/files
  modules/51_nitrogen/ipcc2006_sep16/presolve.gms
  modules/51_nitrogen/rescaled_jan21/declarations.gms
  modules/51_nitrogen/rescaled_jan21/equations.gms
  modules/51_nitrogen/rescaled_jan21/input.gms
  modules/51_nitrogen/rescaled_jan21/input/files
  modules/51_nitrogen/rescaled_jan21/presolve.gms
  modules/52_carbon/normal_dec17/input.gms
  modules/52_carbon/off/input.gms
  modules/56_ghg_policy/price_jan20/sets.gms
  modules/59_som/cellpool_aug16/input.gms
  modules/59_som/static_jan19/declarations.gms
  modules/59_som/static_jan19/input.gms
  modules/59_som/static_jan19/input/files
  modules/59_som/static_jan19/presolve.gms
  modules/59_som/static_jan19/sets.gms
  modules/60_bioenergy/1stgen_priced_dec18/sets.gms
  modules/73_timber/default/declarations.gms
  modules/80_optimization/lp_nlp_apr17/input.gms
  modules/80_optimization/nlp_apr17/input.gms
  modules/80_optimization/nlp_par/input.gms
  scripts/npi_ndc/start_npi_ndc.R
  scripts/output/comparison_validation.R
  scripts/output/projects/inms_reporting_cell.R
  scripts/output/projects/inms_reporting_reg.R
  scripts/start/extra/lpjml_addon.R
  scripts/start/lpjml5.R
  scripts/start/projects/forestry.R
  scripts/start/projects/forestry_lpjml_addon.R
  scripts/start/projects/project_LAMACLIMA.R
  scripts/start/projects/project_inms2.R
  scripts/start/projects/sticky.R
  scripts/start/test_runs_rc.R
Labels: Major, High risk

#319 country-specific set-aside shares
  CHANGELOG.md
  scripts/output/extra/disaggregation.R
Labels: Minor, Low risk

#322 hot fix corrupt default cfg
  config/default.cfg
Labels: bugfix

#321 Bugfix for exo trade runs incomaptible with dynamic forestry realization and trade module
  CHANGELOG.md
  config/default.cfg
  main.gms
  modules/21_trade/exo/input.gms
  modules/21_trade/exo/not_used.txt
  modules/21_trade/exo/preloop.gms
  modules/21_trade/exo/realization.gms
  modules/32_forestry/dynamic_feb21/not_used.txt
  modules/32_forestry/module.gms
  modules/32_forestry/static_sep16/declarations.gms
  modules/32_forestry/static_sep16/not_used.txt
  modules/32_forestry/static_sep16/postsolve.gms
  modules/32_forestry/static_sep16/preloop.gms
  modules/32_forestry/static_sep16/presolve.gms
  modules/32_forestry/static_sep16/realization.gms
  modules/35_natveg/module.gms
  modules/35_natveg/static/declarations.gms
  modules/35_natveg/static/not_used.txt
  modules/35_natveg/static/postsolve.gms
  modules/35_natveg/static/preloop.gms
  modules/35_natveg/static/presolve.gms
  modules/35_natveg/static/realization.gms
  modules/35_natveg/static/sets.gms
Labels: Minor, Low risk, bugfix

#323 Correction of exo equations (h and i) in trade
  CHANGELOG.md
  modules/21_trade/exo/declarations.gms
  modules/21_trade/exo/equations.gms
  modules/21_trade/exo/input.gms
  modules/21_trade/off/declarations.gms
  modules/21_trade/off/not_used.txt
  modules/21_trade/off/preloop.gms
Labels: Minor, Low risk, bugfix

#324 fixed compilation error in nlp_par realization
  CHANGELOG.md
  modules/80_optimization/nlp_par/solve.gms
Labels: Minor, Low risk, bugfix

#317 Peatland Module on by default
  CHANGELOG.md
  config/default.cfg
  scripts/start/test_runs2.R
Labels: Minor, High risk

#327 Rename SSP2Ariadne to SSP2EU
  config/default.cfg
  modules/09_drivers/aug17/input.gms
  modules/09_drivers/aug17/sets.gms
Labels: Low risk, bugfix

#328 fixed rare infeasibility in peatland "on" realization
  CHANGELOG.md
  config/default.cfg
  modules/58_peatland/on/declarations.gms
  modules/58_peatland/on/equations.gms
  modules/58_peatland/on/input.gms
  modules/58_peatland/on/postsolve.gms
Labels: High risk, bugfix

#326 New scenario (Tland) in scenario config
  CHANGELOG.md
  config/scenario_config.csv
  scripts/start/projects/project_GCS.R
Labels: Minor, Medium risk
