Repository magpiemodel/magpie, pull requests merged in 2022-12, with the labels that each got.

#487 semi-natural vegetation in cropland areas rework
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  config/scenario_fsec.csv
  modules/10_land/input/files
  modules/10_land/landmatrix_dec18/input.gms
  modules/22_land_conservation/area_based_apr22/input.gms
  modules/22_land_conservation/area_based_apr22/preloop.gms
  modules/30_crop/endo_apr21/declarations.gms
  modules/30_crop/endo_apr21/equations.gms
  modules/30_crop/endo_apr21/input.gms
  modules/30_crop/endo_apr21/input/files
  modules/30_crop/endo_apr21/postsolve.gms
  modules/30_crop/endo_apr21/preloop.gms
  modules/30_crop/endo_apr21/presolve.gms
  modules/30_crop/penalty_apr22/declarations.gms
  modules/30_crop/penalty_apr22/equations.gms
  modules/30_crop/penalty_apr22/input.gms
  modules/30_crop/penalty_apr22/input/files
  modules/30_crop/penalty_apr22/postsolve.gms
  modules/30_crop/penalty_apr22/preloop.gms
  modules/30_crop/penalty_apr22/presolve.gms
  modules/30_crop/rotation_apr22/declarations.gms
  modules/30_crop/rotation_apr22/equations.gms
  modules/30_crop/rotation_apr22/input.gms
  modules/30_crop/rotation_apr22/input/files
  modules/30_crop/rotation_apr22/postsolve.gms
  modules/30_crop/rotation_apr22/preloop.gms
  modules/30_crop/rotation_apr22/presolve.gms
Labels: enhancement, Medium risk

#490 bugfix in extra/disaggregation.R
  scripts/output/extra/disaggregation.R
  scripts/output/extra/disaggregation_BII.R
Labels: Low risk, bugfix

#488 PR template adjustment, undefault validation_short
  .github/pull_request_template.md
  .gitignore
  CHANGELOG.md
  config/default.cfg
  scripts/start/compilation_check.R
Labels: Minor, Low risk

#492 Efp
  CHANGELOG.md
  config/default.cfg
  core/macros.gms
  main.gms
  modules/42_water_demand/agr_sector_aug13/declarations.gms
  modules/42_water_demand/agr_sector_aug13/input.gms
  modules/42_water_demand/agr_sector_aug13/preloop.gms
  modules/42_water_demand/agr_sector_aug13/presolve.gms
  modules/42_water_demand/agr_sector_aug13/realization.gms
  modules/42_water_demand/all_sectors_aug13/declarations.gms
  modules/42_water_demand/all_sectors_aug13/input.gms
  modules/42_water_demand/all_sectors_aug13/preloop.gms
  modules/42_water_demand/all_sectors_aug13/presolve.gms
  modules/42_water_demand/all_sectors_aug13/realization.gms
  modules/42_water_demand/all_sectors_aug13/sets.gms
  modules/42_water_demand/input/files
Labels: Minor, Medium risk

#493 Add reporting script to output that generates a short mif for REMIND
  CHANGELOG.md
  scripts/output/extra/reportMAgPIE2REMIND.R
Labels: Minor, Low risk
