Repository magpiemodel/magpie, pull requests merged in 2022-09, with the labels that each got.

#441 Health impacts output script
  .gitignore
  CHANGELOG.md
  scripts/output/projects/FSEC_mergeDietaryIndicators.R
  scripts/output/projects/FSEC_nitrogenPollution.R
  scripts/output/projects/FSEC_reportHealthImpacts.R
Labels: enhancement, Low risk

#448 Output script "FSEC_SimonDietz"
  CHANGELOG.md
  scripts/output/projects/FSEC_SimonDietz.R
  scripts/projects/fsec.R
Labels: enhancement, Low risk

#450 Creation of FSDP_process & revision of FSDP_collect
  CHANGELOG.md
  scripts/output/projects/FSDP_collect.R
  scripts/output/projects/FSDP_process.R
  scripts/output/projects/FSEC_mergeDietaryIndicators.R
  scripts/output/projects/FSEC_reportHealthImpacts.R
  scripts/output/projects/fsdp_merge_report.R
  scripts/output/projects/fsdp_reporting_reg.R
  scripts/projects/fsec.R
Labels: enhancement, Low risk

#453 Fix SOM regrowth and disturbance loss corrections
  CHANGELOG.md
  config/default.cfg
  main.gms
  modules/10_land/feb15/declarations.gms
  modules/10_land/landmatrix_dec18/declarations.gms
  modules/42_water_demand/agr_sector_aug13/declarations.gms
  modules/42_water_demand/agr_sector_aug13/input.gms
  modules/42_water_demand/agr_sector_aug13/postsolve.gms
  modules/42_water_demand/all_sectors_aug13/declarations.gms
  modules/42_water_demand/all_sectors_aug13/input.gms
  modules/57_maccs/on_sep16/input.gms
  modules/59_som/cellpool_aug16/declarations.gms
  modules/59_som/cellpool_aug16/postsolve.gms
  modules/59_som/cellpool_aug16/preloop.gms
  modules/59_som/cellpool_aug16/presolve.gms
  modules/59_som/cellpool_aug16/realization.gms
Labels: Minor, Medium risk, bugfix

#455 Changes for newest set of FSEC runs
  CHANGELOG.md
  config/default.cfg
  config/scenario_fsec.csv
  modules/13_tc/endo_jan22/presolve.gms
  modules/56_ghg_policy/price_jan20/sets.gms
  scripts/output/projects/FSDP_collect.R
  scripts/output/projects/FSDP_process.R
  scripts/output/projects/FSEC_water.R
  scripts/output/rds_report.R
  scripts/projects/fsec.R
  scripts/start/extra/recalibrate_FSEC.R
  scripts/start/projects/project_FSEC_Scenarios.R
Labels: Low risk, Medium risk

#427 Add biomass demand for bioplastics in 62_material
  CHANGELOG.md
  config/default.cfg
  modules/62_material/exo_flexreg_apr16/declarations.gms
  modules/62_material/exo_flexreg_apr16/equations.gms
  modules/62_material/exo_flexreg_apr16/input.gms
  modules/62_material/exo_flexreg_apr16/postsolve.gms
  modules/62_material/exo_flexreg_apr16/preloop.gms
  modules/62_material/exo_flexreg_apr16/presolve.gms
  modules/62_material/exo_flexreg_apr16/realization.gms
  modules/62_material/input/files
  modules/62_material/module.gms
Labels: enhancement, Medium risk
