Repository magpiemodel/magpie, pull requests merged in 2022-08, with the labels that each got.

#422 bugfix missing years in f43_wat_avail
  CHANGELOG.md
  modules/43_water_availability/total_water_aug13/input.gms
  modules/43_water_availability/total_water_aug13/preloop.gms
  scripts/start/projects/paper_ClimNat.R
  scripts/start/projects/paper_ClimNat2.R
  scripts/start/projects/paper_scp.R
  scripts/start/projects/project_gwpstar.R
  scripts/start/projects/project_vivid.R
Labels: Minor, High risk, bugfix

#425 new MACCs data set from PBL
  CHANGELOG.md
  modules/57_maccs/input/files
  modules/57_maccs/on_sep16/input.gms
  modules/57_maccs/on_sep16/preloop.gms
  modules/57_maccs/on_sep16/sets.gms
Labels: Minor, Medium risk

#426 FSEC modeling script for global runs
  CHANGELOG.md
  config/default.cfg
  config/scenario_fsec.csv
  modules/13_tc/endo_jan22/presolve.gms
  modules/15_food/anthro_iso_jun22/input.gms
  scripts/output/merge_report.R
  scripts/output/projects/FSDP_collect.R
  scripts/output/projects/agmip_merge_report.R
  scripts/output/projects/agmip_report.R
  scripts/output/projects/fsdp_merge_report.R
  scripts/output/projects/inms_merge_report.R
  scripts/output/projects/inms_reporting_reg.R
  scripts/output/rds_report.R
  scripts/output/rds_report_iso.R
  scripts/projects/fsec.R
  scripts/start/extra/recalibrate_FSEC.R
  scripts/start/extra/recalibrate_FSEC_agroecologyTest.R
  scripts/start/projects/project_FSEC_Scenarios.R
  scripts/start/projects/project_FSEC_Scenarios_agroecologyTest.R
  scripts/start/test_runs.R
Labels: Low risk, Medium risk

#429 added projects/FSEC_cropDiversityGrid.R
  CHANGELOG.md
  scripts/output/projects/FSDP_collect.R
  scripts/output/projects/FSEC_cropDiversityGrid.R
Labels: enhancement, Low risk

#435 blackmagicc output runscript
  CHANGELOG.md
  scripts/output/runBlackmagicc.R
  scripts/projects/fsec.R
Labels: enhancement, Low risk

#436 Introduce logs folder
  CHANGELOG.md
  output.R
  start.R
Labels: enhancement, Low risk

#439 update FSDP_collect script
  scripts/output/projects/FSDP_collect.R
Labels: Minor, Low risk

#440 bugfix highres output script
  scripts/output/extra/highres.R
Labels: Minor, Low risk
