Repository magpiemodel/magpie, pull requests merged in 2022-04, with the labels that each got.

#388 Disaggregation script from MAgPIE outputs to LUH2-ISIMIP3b
  CHANGELOG.md
  scripts/output/extra/disaggregation_LUH2.R
Labels: Minor, Low risk

#391 Add GDP share constraint for tech cost
  CHANGELOG.md
  config/default.cfg
  modules/13_tc/endo_jan22/input.gms
  modules/13_tc/endo_jan22/presolve.gms
  modules/13_tc/exo/not_used.txt
Labels: Minor, Medium risk

#390 replace magpie with magpie4, bugfix
  CHANGELOG.md
  scripts/output/extra/emulator.R
  scripts/start/extra/emulator.R
Labels: Minor, Low risk, bugfix
