Repository magpiemodel/magpie, pull requests merged in 2022-10, with the labels that each got.

#454 minimum wage scneario
  CHANGELOG.md
  CITATION.cff
  config/default.cfg
  modules/36_employment/exo_may22/declarations.gms
  modules/36_employment/exo_may22/equations.gms
  modules/36_employment/exo_may22/input.gms
  modules/36_employment/exo_may22/preloop.gms
  modules/36_employment/exo_may22/presolve.gms
  modules/36_employment/exo_may22/realization.gms
  modules/36_employment/exo_may22/sets.gms
  modules/36_employment/module.gms
  modules/38_factor_costs/mixed_reg_feb17/declarations.gms
  modules/38_factor_costs/mixed_reg_feb17/equations.gms
  modules/38_factor_costs/mixed_reg_feb17/input.gms
  modules/38_factor_costs/mixed_reg_feb17/input/files
  modules/38_factor_costs/mixed_reg_feb17/not_used.txt
  modules/38_factor_costs/mixed_reg_feb17/postsolve.gms
  modules/38_factor_costs/mixed_reg_feb17/preloop.gms
  modules/38_factor_costs/mixed_reg_feb17/presolve.gms
  modules/38_factor_costs/mixed_reg_feb17/realization.gms
  modules/38_factor_costs/mixed_reg_feb17/scaling.gms
  modules/38_factor_costs/mixed_reg_feb17/sets.gms
  modules/38_factor_costs/module.gms
  modules/38_factor_costs/per_ton_fao_may22/declarations.gms
  modules/38_factor_costs/per_ton_fao_may22/equations.gms
  modules/38_factor_costs/per_ton_fao_may22/not_used.txt
  modules/38_factor_costs/per_ton_fao_may22/postsolve.gms
  modules/38_factor_costs/sticky_feb18/declarations.gms
  modules/38_factor_costs/sticky_feb18/equations.gms
  modules/38_factor_costs/sticky_feb18/input.gms
  modules/38_factor_costs/sticky_feb18/not_used.txt
  modules/38_factor_costs/sticky_feb18/presolve.gms
  modules/38_factor_costs/sticky_labor/declarations.gms
  modules/38_factor_costs/sticky_labor/equations.gms
  modules/38_factor_costs/sticky_labor/input.gms
  modules/38_factor_costs/sticky_labor/not_used.txt
  modules/38_factor_costs/sticky_labor/postsolve.gms
  modules/38_factor_costs/sticky_labor/preloop.gms
  modules/38_factor_costs/sticky_labor/presolve.gms
  modules/38_factor_costs/sticky_labor/realization.gms
  modules/70_livestock/fbask_jan16/declarations.gms
  modules/70_livestock/fbask_jan16/equations.gms
Labels: enhancement, High risk, bugfix

#460 Pull Request tweaks
  .github/pull_request_template.md
  CHANGELOG.md
  scripts/start/test_runs.R
Labels: enhancement, Low risk

#457 Inclusion of AQUASTAT calibration factors for yields
  CHANGELOG.md
  config/default.cfg
  literature.bib
  modules/14_yields/managementcalib_aug19/declarations.gms
  modules/14_yields/managementcalib_aug19/input.gms
  modules/14_yields/managementcalib_aug19/input/files
  modules/14_yields/managementcalib_aug19/preloop.gms
  modules/14_yields/managementcalib_aug19/realization.gms
  modules/14_yields/module.gms
  modules/18_residues/flexreg_apr16/equations.gms
  modules/18_residues/flexreg_apr16/input.gms
  modules/18_residues/off/input.gms
  modules/36_employment/exo_may22/declarations.gms
  modules/36_employment/exo_may22/preloop.gms
  modules/42_water_demand/agr_sector_aug13/equations.gms
  modules/42_water_demand/all_sectors_aug13/equations.gms
  modules/50_nr_soil_budget/macceff_aug22/declarations.gms
  scripts/start_functions.R
Labels: enhancement, High risk

#461 use gams status as exit code
  CHANGELOG.md
  scripts/run_submit/submit.R
Labels: Low risk

#463 add urban area to soil C tracking (with natural soil C as proxy)
  CHANGELOG.md
  modules/14_yields/managementcalib_aug19/input.gms
  modules/18_residues/off/realization.gms
  modules/34_urban/exo_nov21/presolve.gms
  modules/34_urban/static/presolve.gms
  modules/52_carbon/normal_dec17/input.gms
  modules/59_som/cellpool_aug16/sets.gms
  modules/59_som/static_jan19/sets.gms
Labels: Minor, Medium risk, bugfix

#465 Updated FSEC start script
  CHANGELOG.md
  config/default.cfg
  config/scenario_fsec.csv
  modules/18_residues/flexreg_apr16/equations.gms
  modules/36_employment/exo_may22/preloop.gms
  modules/50_nr_soil_budget/macceff_aug22/declarations.gms
  modules/59_som/cellpool_aug16/postsolve.gms
  modules/59_som/cellpool_aug16/preloop.gms
  modules/59_som/cellpool_aug16/presolve.gms
  scripts/projects/fsec.R
  scripts/start/extra/recalibrate_FSEC.R
  scripts/start/projects/project_FSEC_Scenarios.R
Labels: Low risk

#466 Update additional data revision number adding ecoSysProt scenarios
  CHANGELOG.md
  config/default.cfg
  modules/56_ghg_policy/price_aug22/sets.gms
Labels: Minor, Low risk

#467 Added new dietary scenarios to FSDP_process
  scripts/output/projects/FSDP_process.R
Labels: Minor, Low risk
