Repository magpiemodel/magpie, pull requests merged in 2022-07, with the labels that each got.

#401 Addition of irrigation water pumping costs for India
  CHANGELOG.md
  config/default.cfg
  main.gms
  modules/11_costs/default/equations.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/declarations.gms
  modules/42_water_demand/agr_sector_aug13/declarations.gms
  modules/42_water_demand/agr_sector_aug13/equations.gms
  modules/42_water_demand/agr_sector_aug13/input.gms
  modules/42_water_demand/agr_sector_aug13/presolve.gms
  modules/42_water_demand/all_sectors_aug13/declarations.gms
  modules/42_water_demand/all_sectors_aug13/equations.gms
  modules/42_water_demand/all_sectors_aug13/input.gms
  modules/42_water_demand/all_sectors_aug13/postsolve.gms
  modules/42_water_demand/all_sectors_aug13/presolve.gms
  modules/42_water_demand/input/files
  modules/43_water_availability/total_water_aug13/declarations.gms
  modules/43_water_availability/total_water_aug13/input.gms
  modules/43_water_availability/total_water_aug13/preloop.gms
  scripts/start/projects/fable_india.R
Labels: enhancement, Medium risk

#409 Update fable_india start script
  scripts/start/projects/fable_india.R
Labels: bugfix

#414 Merge 4.5.0 back into develop
  .zenodo.json
  CHANGELOG.md
  CITATION.cff
  README.md
  scripts/start/projects/fable_india.R
Labels: Minor, Low risk

#408 Outputs scripts for FSDP runs
  CHANGELOG.md
  scripts/output/extra/disaggregation_BII.R
  scripts/output/projects/FSDP_collect.R
  scripts/output/rds_report_iso.R
  scripts/start/projects/project_FSEC_Scenarios.R
  scripts/start/projects/project_FSEC_Scenarios_agroecologyTest.R
Labels: enhancement, Minor, Low risk

#419 Develop2
  CHANGELOG.md
  modules/15_food/anthro_iso_jun22/input.gms
  modules/15_food/input/files
Labels: Minor, Low risk, bugfix

#418 Update input revision number to 4.75
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  main.gms
  modules/70_livestock/fbask_jan16/preloop.gms
  modules/70_livestock/fbask_jan16/sets.gms
Labels: High risk

#415 Added primary and secondary other land adjustment to BII disaggregattion
  CHANGELOG.md
  scripts/output/extra/disaggregation_BII.R
  scripts/start/projects/project_FSEC_Scenarios.R
Labels: enhancement, Low risk

#421 updated literature
  .github/pull_request_template.md
  CHANGELOG.md
  literature.bib
Labels: Minor, Low risk, bugfix
