Repository magpiemodel/magpie, pull requests merged in 2022-01, with the labels that each got.

#359 small bugfixes
  CHANGELOG.md
  config/default.cfg
  modules/18_residues/off/declarations.gms
  modules/18_residues/off/postsolve.gms
  modules/50_nr_soil_budget/off/declarations.gms
  modules/50_nr_soil_budget/off/postsolve.gms
  modules/50_nr_soil_budget/off/preloop.gms
  modules/59_som/static_jan19/presolve.gms
  modules/62_material/exo_flexreg_apr16/declarations.gms
  modules/62_material/exo_flexreg_apr16/equations.gms
  modules/62_material/exo_flexreg_apr16/presolve.gms
  modules/80_optimization/nlp_par/solve.gms
  scripts/calibration/calc_calib.R
  scripts/calibration/landconversion_cost.R
  scripts/start/projects/test_country.R
Labels: Minor, Low risk, bugfix

#361 Updated non-agricultural water use scenarios to WATERGAP
  CHANGELOG.md
  config/default.cfg
  core/sets.gms
  literature.bib
  modules/42_water_demand/agr_sector_aug13/declarations.gms
  modules/42_water_demand/agr_sector_aug13/input.gms
  modules/42_water_demand/agr_sector_aug13/presolve.gms
  modules/42_water_demand/agr_sector_aug13/sets.gms
  modules/42_water_demand/all_sectors_aug13/declarations.gms
  modules/42_water_demand/all_sectors_aug13/equations.gms
  modules/42_water_demand/all_sectors_aug13/input.gms
  modules/42_water_demand/all_sectors_aug13/presolve.gms
  modules/42_water_demand/all_sectors_aug13/realization.gms
  modules/42_water_demand/all_sectors_aug13/sets.gms
  modules/42_water_demand/module.gms
  modules/43_water_availability/total_water_aug13/equations.gms
Labels: Medium risk

#362 Updated input and renamed FF_BH to BH_IFL
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  main.gms
  modules/35_natveg/dynamic_feb21/preloop.gms
  modules/35_natveg/dynamic_feb21/realization.gms
  modules/35_natveg/dynamic_feb21/sets.gms
  modules/42_water_demand/agr_sector_aug13/declarations.gms
  modules/42_water_demand/all_sectors_aug13/declarations.gms
  scripts/start/projects/forestry.R
Labels: Minor, Medium risk

#363 updated tutorials link in readme
  README.md
Labels: Minor, Low risk

#365 Fixed misleading warning in config check
  CHANGELOG.md
  scripts/start_functions.R
Labels: Minor, Low risk, bugfix

#366 PR template update: cellular input data in sceanrio_config.csv
  .github/pull_request_template.md
Labels: Minor, Low risk

#368 Replaced config.log and config.Rdata with config.yml
  CHANGELOG.md
  README.md
  config/default.cfg
  main.gms
  modules/42_water_demand/all_sectors_aug13/input.gms
  scripts/output/comparison_validation.R
  scripts/output/deprecated/disaggregation_cropsplit.R
  scripts/output/deprecated/disaggregation_transitions.R
  scripts/output/extra/aff_area.R
  scripts/output/extra/disaggregation.R
  scripts/output/extra/disaggregation_LUH2.R
  scripts/output/extra/emulator.R
  scripts/output/extra/force_runstatistics.R
  scripts/output/extra/highres.R
  scripts/output/extra/validation_existing_report.R
  scripts/output/merge_report.R
  scripts/output/projects/MAgPIE2GAINS.R
  scripts/output/projects/MAgPIE2LPJmL.R
  scripts/output/projects/agmip_merge_report.R
  scripts/output/projects/agmip_report.R
  scripts/output/projects/inms_merge_report.R
  scripts/output/projects/inms_reporting_cell.R
  scripts/output/projects/inms_reporting_reg.R
  scripts/output/projects/peatland.R
  scripts/output/rds_report.R
  scripts/output/validation.R
  scripts/output/validation_short.R
  scripts/performance_test.R
  scripts/run_submit/submit.R
  scripts/start_functions.R
Labels: enhancement, Low risk

#369 bugfix biodiversity value in 34_urban
  CHANGELOG.md
  modules/34_urban/exo_nov21/declarations.gms
  modules/34_urban/exo_nov21/equations.gms
  modules/34_urban/exo_nov21/presolve.gms
  modules/34_urban/module.gms
Labels: Low risk, bugfix

#371 Bug fix in urban module and new disaggregation output script
  CHANGELOG.md
  config/default.cfg
  modules/34_urban/exo_nov21/declarations.gms
  modules/34_urban/exo_nov21/equations.gms
  scripts/output/extra/disaggregation_BII.R
Labels: Minor, Low risk, bugfix

#367 Update input to rev4.67
  config/default.cfg
  scripts/start/extra/recalibrate_realizations.R
Labels: High risk
