Repository magpiemodel/magpie, pull requests merged in 2022-11, with the labels that each got.

#468 Update default MACCs from PBL2007 to PBL2022
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
Labels: Minor, High risk

#469 Update of FSEC scenarios
  CHANGELOG.md
  config/scenario_fsec.csv
  modules/18_residues/flexreg_apr16/equations.gms
  modules/59_som/cellpool_aug16/presolve.gms
  scripts/output/projects/FSDP_collect.R
  scripts/projects/fsec.R
  scripts/start/extra/recalibrate_FSEC.R
Labels: Low risk, bugfix

#471 Bugfix FSDP_collect.R
  scripts/output/projects/FSDP_collect.R
Labels: Low risk, bugfix

#470 Add Supplementary plotting function calls to FSDP_collect.R output script
  modules/21_trade/input/files
  scripts/output/projects/FSDP_collect.R
Labels: Minor, Low risk

#462 Updated SHAPE SDP scenarios and new default for 15_food
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  scripts/start/projects/project_SHAPE.R
Labels: Minor, Medium risk

#474 Clean the coupling interface (remove deletePlus, clean code)
  .zenodo.json
  CHANGELOG.md
  CITATION.cff
  scripts/start_functions.R
Labels: Low risk

#476 Clean the REMIND coupling interface
  CHANGELOG.md
  scripts/start_functions.R
Labels: Low risk

#478 fixed typo
  main.gms
Labels: Low risk, bugfix

#479 FSDP output script update
  scripts/output/projects/FSDP_collect.R
Labels: Minor, Low risk

#483 bugfix s56_limit_ch4_n2o_price default value
  CHANGELOG.md
  config/default.cfg
Labels: Minor, High risk, bugfix

#484 Update add. data rev. adding ecoSysProtAll_agMgmtOff scenario
  config/default.cfg
  modules/56_ghg_policy/price_aug22/sets.gms
Labels: Minor, Low risk
