Repository magpiemodel/magpie, pull requests merged in 2023-11, with the labels that each got.

#604 New realization in peatland module
  CHANGELOG.md
  config/default.cfg
  literature.bib
  modules/32_forestry/dynamic_feb21/declarations.gms
  modules/32_forestry/dynamic_feb21/equations.gms
  modules/32_forestry/dynamic_feb21/postsolve.gms
  modules/32_forestry/dynamic_feb21/preloop.gms
  modules/32_forestry/dynamic_feb21/realization.gms
  modules/32_forestry/module.gms
  modules/56_ghg_policy/price_aug22/sets.gms
  modules/58_peatland/input/files
  modules/58_peatland/module.gms
  modules/58_peatland/off/not_used.txt
  modules/58_peatland/on/equations.gms
  modules/58_peatland/on/not_used.txt
  modules/58_peatland/on/realization.gms
  modules/58_peatland/v2/declarations.gms
  modules/58_peatland/v2/equations.gms
  modules/58_peatland/v2/input.gms
  modules/58_peatland/v2/postsolve.gms
  modules/58_peatland/v2/preloop.gms
  modules/58_peatland/v2/presolve.gms
  modules/58_peatland/v2/realization.gms
  modules/58_peatland/v2/sets.gms
  modules/73_timber/default/realization.gms
Labels: enhancement, Medium risk

#608 bugfix in NPI/NDC calculations
  CHANGELOG.md
  scripts/npi_ndc/start_npi_ndc.R
Labels: Low risk

#609 added switch to turn off yield calib
  CHANGELOG.md
  config/default.cfg
  config/scenario_fsec.csv
  modules/14_yields/managementcalib_aug19/input.gms
  modules/14_yields/managementcalib_aug19/preloop.gms
  scripts/start/extra/recalibrate_FSEC.R
Labels: High risk

#610 use 67k inputdata by default
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  config/scenario_fsec.csv
Labels: High risk, data update

#613 Fix disaggregation scripts to be used with 67k input
  CHANGELOG.md
  scripts/output/extra/disaggregation.R
  scripts/output/extra/disaggregation_LUH2.R
Labels: Low risk, bugfix

#614 Bugfix in grasslands_apr22 pasture realization.
  CHANGELOG.md
  CITATION.cff
  config/default.cfg
  core/sets.gms
  main.gms
  modules/31_past/endo_jun13/not_used.txt
  modules/31_past/grasslands_apr22/input.gms
  modules/31_past/grasslands_apr22/preloop.gms
  modules/31_past/grasslands_apr22/sets.gms
  modules/31_past/input/files
  modules/31_past/static/not_used.txt
Labels: bugfix
