Repository magpiemodel/magpie, pull requests merged in 2023-08, with the labels that each got.

#586 Update input data rev4.88
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
Labels: High risk

#587 Bugfix disaggregation_LUH2.R
  CHANGELOG.md
  DESCRIPTION
  scripts/output/extra/disaggregation.R
  scripts/output/extra/disaggregation_LUH2.R
Labels: Minor, Low risk, bugfix

#583 Remove unnecessary warning for empty magpie runs
  CHANGELOG.md
  scripts/start_functions.R
Labels: Low risk

#591 Extended set of years that are reported to SEALS
  CHANGELOG.md
  scripts/output/extra/reportMAgPIE2SEALS.R
Labels: enhancement, Minor, Low risk

#592 Bugfix pasture management factor
  CHANGELOG.md
  modules/70_livestock/fbask_jan16/presolve.gms
Labels: Minor, Low risk, bugfix
