Repository magpiemodel/magpie, pull requests merged in 2023-05, with the labels that each got.

#557 Update Siebert AEI data
  CHANGELOG.md
  config/default.cfg
  modules/41_area_equipped_for_irrigation/endo_apr13/declarations.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/postsolve.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/preloop.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/presolve.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/sets.gms
  modules/41_area_equipped_for_irrigation/input/files
  modules/41_area_equipped_for_irrigation/static/declarations.gms
  modules/41_area_equipped_for_irrigation/static/input.gms
  modules/41_area_equipped_for_irrigation/static/presolve.gms
  modules/41_area_equipped_for_irrigation/static/sets.gms
  renv/activate.R
  renv/settings.json
Labels: Low risk, data update

#563 Added a scenario for NGFS_o_lowdem
  CHANGELOG.md
  config/scenario_config.csv
Labels: Low risk

#562 update start_functions.R such that different cluster sets are possible
  CHANGELOG.md
  scripts/start_functions.R
Labels: Low risk, Medium risk, bugfix

#564 Bugfix in scenario config
  CHANGELOG.md
  config/scenario_config.csv
  config/scenario_fsec.csv
Labels: bugfix
