Repository magpiemodel/magpie, pull requests merged in 2023-02, with the labels that each got.

#517 fix renv for HR runs
  CHANGELOG.md
  config/default.cfg
  output.R
  scripts/output/extra/highres.R
  scripts/start_functions.R
Labels: Low risk, bugfix

#518 Changes in the best_calib selection criterion
  CHANGELOG.md
  scripts/calibration/calc_calib.R
  scripts/start/extra/recalibrate.R
  scripts/start/extra/recalibrate_realizations.R
Labels: Medium risk

#519 DEPENDENCIES -> DESCRIPTION because of renv snapshot logic
  .Rprofile
  DESCRIPTION
Labels: Low risk

#525 improvements sticky_labor
  CHANGELOG.md
  modules/38_factor_costs/sticky_labor/declarations.gms
  modules/38_factor_costs/sticky_labor/equations.gms
  modules/38_factor_costs/sticky_labor/nl_fix.gms
  modules/38_factor_costs/sticky_labor/nl_relax.gms
  modules/38_factor_costs/sticky_labor/nl_release.gms
  modules/38_factor_costs/sticky_labor/postsolve.gms
  modules/38_factor_costs/sticky_labor/presolve.gms
  modules/38_factor_costs/sticky_labor/realization.gms
Labels: enhancement, Medium risk

#522 Bugfix in Water demand: Remove multicropping factor
  CHANGELOG.md
  modules/18_residues/flexreg_apr16/equations.gms
  modules/18_residues/flexreg_apr16/input.gms
  modules/18_residues/off/input.gms
  modules/42_water_demand/agr_sector_aug13/equations.gms
  modules/42_water_demand/all_sectors_aug13/equations.gms
Labels: Low risk, bugfix

#526 bugfix land restoration
  CHANGELOG.md
  modules/32_forestry/dynamic_feb21/presolve.gms
Labels: Minor, Low risk, bugfix

#527 Update input data to rev4.81 trade margin bugfix
  CHANGELOG.md
  config/default.cfg
  main.gms
Labels: Medium risk

#528 update scenario_config cellular input vector to rev4.81
  config/scenario_config.csv
Labels: Low risk

#530 aff switch
  CHANGELOG.md
  config/default.cfg
  modules/32_forestry/dynamic_feb21/input.gms
  modules/32_forestry/dynamic_feb21/presolve.gms
  modules/56_ghg_policy/price_aug22/input.gms
  modules/56_ghg_policy/price_aug22/preloop.gms
  modules/56_ghg_policy/price_aug22/sets.gms
Labels: enhancement, Minor, Medium risk

#449 Bilateral trade realization
  CHANGELOG.md
  config/default.cfg
  main.gms
  modules/21_trade/input/files
  modules/21_trade/module.gms
  modules/21_trade/selfsuff_reduced_bilateral22/declarations.gms
  modules/21_trade/selfsuff_reduced_bilateral22/equations.gms
  modules/21_trade/selfsuff_reduced_bilateral22/input.gms
  modules/21_trade/selfsuff_reduced_bilateral22/input/files
  modules/21_trade/selfsuff_reduced_bilateral22/postsolve.gms
  modules/21_trade/selfsuff_reduced_bilateral22/preloop.gms
  modules/21_trade/selfsuff_reduced_bilateral22/realization.gms
  modules/21_trade/selfsuff_reduced_bilateral22/scaling.gms
  modules/21_trade/selfsuff_reduced_bilateral22/sets.gms
  modules/21_trade/selfsuff_reduced_bilateral22/trade_pools.png
  modules/38_factor_costs/module.gms
  modules/51_nitrogen/module.gms
Labels: Medium risk

#529 Newest Changes for FSEC models runs
  CHANGELOG.md
  config/scenario_fsec.csv
  literature.bib
  modules/58_peatland/on/postsolve.gms
  modules/58_peatland/on/preloop.gms
  modules/59_som/cellpool_aug16/postsolve.gms
  modules/59_som/cellpool_aug16/presolve.gms
  modules/59_som/cellpool_jan23/postsolve.gms
  modules/59_som/cellpool_jan23/presolve.gms
  output.R
  scripts/output/extra/disaggregation_BII.R
  scripts/output/extra/highres.R
  scripts/output/projects/FSDP_collect.R
  scripts/output/projects/FSDP_process.R
  scripts/output/rds_report.R
  scripts/projects/fsec.R
  scripts/start/extra/recalibrate.R
  scripts/start/extra/recalibrate_FSEC.R
  scripts/start/extra/recalibrate_all.R
  scripts/start/extra/recalibrate_realizations.R
  scripts/start/projects/project_FSEC_Scenarios.R
Labels: Low risk, bugfix

#531 checkNoTabs performance
  .githooks/pre-commit
  .gitignore
  literature.bib
Labels: enhancement, Minor, Low risk
