Repository magpiemodel/magpie, pull requests merged in 2023-10, with the labels that each got.

#598 update of ILO data and hourly labor cost regression
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  config/scenario_fsec.csv
  modules/36_employment/exo_may22/preloop.gms
  modules/36_employment/exo_may22/sets.gms
Labels: Medium risk, data update

#600 bugfixed inputdata rev4.92
  .zenodo.json
  CITATION.cff
  config/default.cfg
Labels: bugfix, data update

#603 bugfix: inputdata rev4.93
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
Labels: bugfix, data update

#602 Clean, update, and improve emulator start and output scripts
  CHANGELOG.md
  config/scenario_config_emulator.csv
  scripts/output/extra/emulator.R
  scripts/start/extra/emulator.R
Labels: Minor, Low risk, bugfix
