Repository magpiemodel/magpie, pull requests merged in 2023-07, with the labels that each got.

#569 Bugfix: in the non-default realization of 30_crop, rotation_apr22, the fallow land term was on the wrong side of the equation.
  CHANGELOG.md
  modules/30_crop/penalty_apr22/equations.gms
  modules/30_crop/rotation_apr22/equations.gms
Labels: Medium risk

#573 remove snapshot support
  .snapshot.Rprofile
  CHANGELOG.md
  scripts/start/Rprofile.R
Labels: Low risk

#572 New output script for reporting land use to SEALS
  CHANGELOG.md
  scripts/output/extra/reportMAgPIE2SEALS.R
Labels: Low risk

#574 added missing changelog from PR571
  CHANGELOG.md
Labels: Minor, bugfix

#578 Update pasture management factor
  CHANGELOG.md
  config/default.cfg
  modules/15_food/anthro_iso_jun22/declarations.gms
  modules/15_food/anthro_iso_jun22/equations.gms
  modules/15_food/anthro_iso_jun22/exodietmacro.gms
  modules/15_food/anthro_iso_jun22/input.gms
  modules/15_food/anthro_iso_jun22/preloop.gms
  modules/15_food/anthro_iso_jun22/sets.gms
  modules/15_food/anthropometrics_jan18/declarations.gms
  modules/15_food/anthropometrics_jan18/equations.gms
  modules/15_food/anthropometrics_jan18/input.gms
  modules/15_food/anthropometrics_jan18/intersolve.gms
  modules/15_food/anthropometrics_jan18/preloop.gms
  modules/15_food/anthropometrics_jan18/presolve.gms
  modules/15_food/anthropometrics_jan18/sets.gms
  modules/15_food/module.gms
  modules/16_demand/sector_may15/sets.gms
  modules/70_livestock/fbask_jan16/declarations.gms
  modules/70_livestock/fbask_jan16/presolve.gms
Labels: Minor, High risk

#580 fixed disaggregation inaccuracies in luscale
  CHANGELOG.md
  DESCRIPTION
Labels: enhancement, Low risk, bugfix
