Repository magpiemodel/magpie, pull requests merged in 2023-03, with the labels that each got.

#536 Disaggregation to 0.5° takes land conservation into account
  CHANGELOG.md
  config/default.cfg
  scripts/output/extra/disaggregation.R
  scripts/output/extra/disaggregation_BII.R
Labels: Low risk

#539 Bugfix NDC CO2 emission pricing in coupled and standalone runs
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  modules/56_ghg_policy/price_aug22/input.gms
  modules/56_ghg_policy/price_aug22/preloop.gms
  scripts/start/test_runs.R
  scripts/start_functions.R
Labels: Minor, Medium risk, bugfix

#540 bugfix pasture suitabilty
  CHANGELOG.md
  modules/31_past/endo_jun13/not_used.txt
  modules/31_past/grasslands_apr22/preloop.gms
  modules/31_past/static/not_used.txt
Labels: Minor, Low risk, bugfix

#544 fix for divergance in demand in 2020 for capitalSubst scenario
  modules/38_factor_costs/sticky_labor/presolve.gms
Labels: Low risk, bugfix

#545 max calib factor divergence to max divergence
  CHANGELOG.md
  scripts/calibration/calc_calib.R
Labels: Low risk, bugfix

#543 add cluster_resolution output script
  CHANGELOG.md
  scripts/output/extra/land_cluster_shapefile.R
Labels: Low risk

#546 bugfix test-runs start script
  scripts/start/test_runs.R
Labels: Minor, Low risk, bugfix
