Repository magpiemodel/magpie, pull requests merged in 2023-04, with the labels that each got.

#550 on.exit -> withr::defer
  scripts/insertheader/insertheader.R
  scripts/output/extra/disaggregation.R
  scripts/output/extra/disaggregation_LUH2.R
  scripts/output/extra/emulator.R
  scripts/output/projects/inms_reporting_reg.R
  scripts/performance_test.R
  scripts/start/Rprofile.R
  scripts/start_functions.R
Labels: Low risk, bugfix

#547 Changes for v36 of FSEC
  config/default.cfg
  config/scenario_fsec.csv
  scripts/output/projects/FSDP_collect.R
  scripts/projects/fsec.R
  scripts/start/extra/recalibrate_FSEC.R
  scripts/start/projects/project_FSEC_Scenarios.R
Labels: Low risk

#541 Introducing exogenous diets for India
  CHANGELOG.md
  config/default.cfg
  main.gms
  modules/15_food/anthro_iso_jun22/exodietmacro.gms
  modules/15_food/anthro_iso_jun22/input.gms
  modules/15_food/anthro_iso_jun22/preloop.gms
  modules/15_food/input/files
  modules/38_factor_costs/module.gms
Labels: enhancement, Medium risk

#551 show snapshot errors
  output.R
  scripts/start_functions.R
Labels: Minor, bugfix

#552 added output script for forest area change
  CHANGELOG.md
  scripts/output/extra/ForestChangeCluster.R
Labels: enhancement, Minor, Low risk

#553 Made NPI and NDC calculatiosn ready for 67k cells and removed reference to semantic versioning
  CHANGELOG.md
  config/default.cfg
  scripts/npi_ndc/start_npi_ndc.R
Labels: Minor, bugfix

#554 update scenario_config SSP2EU + GHG emissions pricing policies
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  core/sets.gms
  main.gms
  modules/09_drivers/aug17/input.gms
  modules/09_drivers/aug17/sets.gms
  modules/56_ghg_policy/price_aug22/sets.gms
Labels: Minor, Low risk
