Repository magpiemodel/magpie, pull requests merged in 2023-01, with the labels that each got.

#495 FSEC v28
  CHANGELOG.md
  config/scenario_fsec.csv
  modules/80_optimization/nlp_par/solve.gms
  scripts/output/extra/highres.R
  scripts/output/projects/FSDP_collect.R
  scripts/output/projects/FSDP_process.R
  scripts/output/projects/FSEC_StevenLord.R
  scripts/output/projects/FSEC_water.R
  scripts/projects/fsec.R
  scripts/start/extra/recalibrate_FSEC.R
  scripts/start/projects/project_FSEC_Scenarios.R
Labels: Low risk

#496 employment from maccs
  CHANGELOG.md
  modules/11_costs/default/equations.gms
  modules/36_employment/exo_may22/declarations.gms
  modules/36_employment/exo_may22/equations.gms
  modules/36_employment/exo_may22/postsolve.gms
  modules/36_employment/exo_may22/preloop.gms
  modules/36_employment/exo_may22/presolve.gms
  modules/36_employment/exo_may22/realization.gms
  modules/36_employment/module.gms
  modules/38_factor_costs/per_ton_fao_may22/declarations.gms
  modules/38_factor_costs/per_ton_fao_may22/equations.gms
  modules/38_factor_costs/per_ton_fao_may22/input.gms
  modules/38_factor_costs/per_ton_fao_may22/presolve.gms
  modules/38_factor_costs/sticky_feb18/declarations.gms
  modules/38_factor_costs/sticky_feb18/equations.gms
  modules/38_factor_costs/sticky_feb18/input.gms
  modules/38_factor_costs/sticky_feb18/presolve.gms
  modules/38_factor_costs/sticky_labor/declarations.gms
  modules/38_factor_costs/sticky_labor/input.gms
  modules/38_factor_costs/sticky_labor/presolve.gms
  modules/57_maccs/on_aug22/declarations.gms
  modules/57_maccs/on_aug22/equations.gms
  modules/57_maccs/on_aug22/postsolve.gms
  modules/57_maccs/on_aug22/scaling.gms
Labels: enhancement, Medium risk

#482 renv integration
  .Rbuildignore
  .Rprofile
  .gitignore
  .lintr
  .snapshot.Rprofile
  CHANGELOG.md
  DEPENDENCIES
  Makefile
  README.md
  output.R
  renv/.gitignore
  renv/activate.R
  renv/settings.dcf
  scripts/start/Rprofile.R
  scripts/start_functions.R
  start.R
Labels: High risk

#498 Update SHAPE SDP scenario switches
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
Labels: Minor, Medium risk

#500 added sub-national validation output script for India
  CHANGELOG.md
  scripts/output/projects/FABLE_India_subnational_validation.R
Labels: Low risk

#499 labor share target in crop production
  CHANGELOG.md
  config/default.cfg
  modules/11_costs/default/equations.gms
  modules/30_crop/endo_apr21/input.gms
  modules/38_factor_costs/per_ton_fao_may22/declarations.gms
  modules/38_factor_costs/per_ton_fao_may22/postsolve.gms
  modules/38_factor_costs/per_ton_fao_may22/scaling.gms
  modules/38_factor_costs/per_ton_fao_may22/sets.gms
  modules/38_factor_costs/sticky_feb18/declarations.gms
  modules/38_factor_costs/sticky_feb18/postsolve.gms
  modules/38_factor_costs/sticky_feb18/scaling.gms
  modules/38_factor_costs/sticky_feb18/sets.gms
  modules/38_factor_costs/sticky_labor/declarations.gms
  modules/38_factor_costs/sticky_labor/equations.gms
  modules/38_factor_costs/sticky_labor/input.gms
  modules/38_factor_costs/sticky_labor/postsolve.gms
  modules/38_factor_costs/sticky_labor/preloop.gms
  modules/38_factor_costs/sticky_labor/presolve.gms
  modules/38_factor_costs/sticky_labor/scaling.gms
  modules/38_factor_costs/sticky_labor/sets.gms
  modules/56_ghg_policy/price_aug22/input.gms
  modules/57_maccs/on_aug22/declarations.gms
  modules/57_maccs/on_aug22/postsolve.gms
  modules/57_maccs/on_aug22/scaling.gms
  modules/70_livestock/fbask_jan16/declarations.gms
  modules/70_livestock/fbask_jan16/postsolve.gms
  modules/70_livestock/scaling.gms
  scripts/output/projects/FSDP_collect.R
Labels: Medium risk

#497 Add an empty standalone model for testing purposes
  CHANGELOG.md
  scripts/start/extra/empty_model.R
  scripts/start_functions.R
  standalone/.gitignore
Labels: Low risk

#505 Bugfix Food and Material module results until 2020
  CHANGELOG.md
  modules/15_food/anthro_iso_jun22/exodietmacro.gms
  modules/62_material/exo_flexreg_apr16/equations.gms
  modules/62_material/exo_flexreg_apr16/preloop.gms
  modules/62_material/exo_flexreg_apr16/realization.gms
  modules/62_material/module.gms
Labels: Minor, High risk, bugfix

#506 Add new SOM realization (updated factors)
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  config/scenario_fsec.csv
  literature.bib
  main.gms
  modules/31_past/grasslands_apr22/realization.gms
  modules/38_factor_costs/sticky_labor/input.gms
  modules/59_som/cellpool_jan23/declarations.gms
  modules/59_som/cellpool_jan23/equations.gms
  modules/59_som/cellpool_jan23/input.gms
  modules/59_som/cellpool_jan23/input/files
  modules/59_som/cellpool_jan23/postsolve.gms
  modules/59_som/cellpool_jan23/preloop.gms
  modules/59_som/cellpool_jan23/presolve.gms
  modules/59_som/cellpool_jan23/realization.gms
  modules/59_som/cellpool_jan23/scaling.gms
  modules/59_som/cellpool_jan23/sets.gms
  modules/59_som/module.gms
Labels: enhancement, Minor, Medium risk

#507 bugfix for dots in title
  CHANGELOG.md
  scripts/start_functions.R
Labels: Low risk

#509 Bugfix cropland module - consistent results until 2020
  CHANGELOG.md
  modules/30_crop/endo_apr21/input.gms
  modules/30_crop/endo_apr21/presolve.gms
  modules/30_crop/penalty_apr22/input.gms
  modules/30_crop/penalty_apr22/presolve.gms
  modules/30_crop/rotation_apr22/input.gms
  modules/30_crop/rotation_apr22/presolve.gms
Labels: Minor, High risk, bugfix

#508 New overweight scenario (half_overweight)
  CHANGELOG.md
  config/default.cfg
  config/scenario_fsec.csv
  modules/15_food/anthro_iso_jun22/exodietmacro.gms
  modules/15_food/anthro_iso_jun22/input.gms
  scripts/start/projects/project_FSEC_Scenarios.R
  scripts/start/projects/test_diets.R
Labels: Minor, Medium risk

#512 Added restart points and automatic restart support
  CHANGELOG.md
  config/default.cfg
  core/calculations.gms
  main.gms
  scripts/run_submit/submit.R
  scripts/run_submit/submit_standby_dayMax.sh
Labels: enhancement, Minor, High risk

#514 fix output.R running via slurm checking for updates
  Makefile
  output.R
Labels: Low risk, bugfix

#513 FSEC version 30
  CHANGELOG.md
  config/scenario_fsec.csv
  modules/14_yields/managementcalib_aug19/nl_fix.gms
  modules/59_som/cellpool_aug16/presolve.gms
  modules/59_som/cellpool_jan23/presolve.gms
  scripts/output/projects/FSDP_collect.R
  scripts/projects/fsec.R
  scripts/start/extra/recalibrate_FSEC.R
  scripts/start/projects/project_FSEC_Scenarios.R
Labels: Low risk

#515 Biodiversity Module - bugfix for high-resolution script
  CHANGELOG.md
  config/default.cfg
  config/scenario_fsec.csv
  modules/44_biodiversity/bii_target/declarations.gms
  modules/44_biodiversity/bii_target/equations.gms
  modules/44_biodiversity/bii_target/postsolve.gms
  modules/44_biodiversity/bii_target/preloop.gms
  modules/44_biodiversity/bii_target/presolve.gms
  scripts/output/extra/highres.R
  scripts/projects/fsec.R
  scripts/run_submit/submit_standby_maxMem_dayMax.sh
Labels: Minor, High risk, bugfix

#516 F inputdata fsec
  CHANGELOG.md
  config/scenario_fsec.csv
  scripts/projects/fsec.R
Labels: Low risk
