Repository magpiemodel/magpie, pull requests merged in 2023-06, with the labels that each got.

#566 show renv snapshot errors
  output.R
  scripts/start_functions.R
Labels: Low risk

#567 added `nocc` and `nocc_hist` options
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  core/sets.gms
  main.gms
  modules/31_past/endo_jun13/not_used.txt
  modules/31_past/grasslands_apr22/input.gms
  modules/31_past/grasslands_apr22/preloop.gms
  modules/31_past/static/not_used.txt
  modules/52_carbon/normal_dec17/input.gms
Labels: enhancement, Minor, Low risk

#570 results folder for highres runs
  CHANGELOG.md
  config/default.cfg
  scripts/output/extra/highres.R
  scripts/start/test_runs.R
Labels: Minor, Low risk
