Repository magpiemodel/magpie, pull requests merged in 2024-10, with the labels that each got.

#729 Adjust US$2005 -> 2017 for data read from REMIND
  CHANGELOG.md
  scripts/start/extra/emulator.R
  scripts/start_functions.R
Labels: Low risk, bugfix

#731 switch to turn off future bioplastic demand
  CHANGELOG.md
  config/default.cfg
  modules/62_material/exo_flexreg_apr16/input.gms
  modules/62_material/exo_flexreg_apr16/preloop.gms
  modules/62_material/exo_flexreg_apr16/presolve.gms
Labels: Low risk

#732 bugfix tree cover on cropland
  CHANGELOG.md
  modules/29_cropland/detail_apr24/presolve.gms
  scripts/start/projects/project_ABCDR.R
Labels: Minor, Low risk, bugfix

#734 update input files to rev4.113
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  config/projects/scenario_config_el2.csv
  config/projects/scenario_config_fsec.csv
  config/scenario_config.csv
  modules/58_peatland/v2/scaling.gms
  scripts/output/extra/resubmit.R
  scripts/start/extra/recalibrateH16.R
  scripts/start/projects/paper_peatlandTax.R
  scripts/start/projects/project_ABCDR.R
  scripts/start/projects/project_EAT2p0.R
Labels: Minor, Low risk

#735 bugfix warning in highres output script
  scripts/output/extra/highres.R
Labels: Minor, Low risk, bugfix

#736 added scenarios to scenario_config
  CHANGELOG.md
  config/scenario_config.csv
Labels: Minor, Low risk

#737 Bugfix age-classes
  CHANGELOG.md
  config/default.cfg
  config/projects/scenario_config_el2.csv
  config/projects/scenario_config_fsec.csv
  config/scenario_config.csv
  core/sets.gms
  literature.bib
  main.gms
  modules/28_ageclass/feb21/preloop.gms
  modules/28_ageclass/feb21/realization.gms
  modules/28_ageclass/module.gms
  modules/28_ageclass/oct24/declarations.gms
  modules/28_ageclass/oct24/input.gms
  modules/28_ageclass/oct24/preloop.gms
  modules/28_ageclass/oct24/presolve.gms
  modules/28_ageclass/oct24/realization.gms
  modules/28_ageclass/oct24/sets.gms
  modules/35_natveg/pot_forest_may24/declarations.gms
  modules/35_natveg/pot_forest_may24/preloop.gms
  scripts/start/extra/recalibrateH16.R
  scripts/start/projects/paper_peatlandTax.R
  scripts/start/projects/project_ABCDR.R
  scripts/start/projects/project_EAT2p0.R
Labels: enhancement, Medium risk, bugfix
