Repository magpiemodel/magpie, pull requests merged in 2024-07, with the labels that each got.

#694 update merge_report and rds_report
  CHANGELOG.md
  scripts/output/merge_report.R
  scripts/output/rds_report.R
  scripts/output/rds_report_iso.R
Labels: Minor, Low risk

#695 Added non-ag. water consumption as output
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  config/scenario_fsec.csv
  modules/42_water_demand/agr_sector_aug13/declarations.gms
  modules/42_water_demand/agr_sector_aug13/presolve.gms
  modules/42_water_demand/agr_sector_aug13/sets.gms
  modules/42_water_demand/all_sectors_aug13/declarations.gms
  modules/42_water_demand/all_sectors_aug13/input.gms
  modules/42_water_demand/all_sectors_aug13/presolve.gms
  modules/42_water_demand/all_sectors_aug13/sets.gms
  scripts/start/projects/project_EAT2p0.R
  scripts/start/projects/project_EAT2p0_DeepDive.R
Labels: Low risk

#696 Use 'find' instead of 'ls' to create the list of reportings available for shinyresults
  scripts/output/rds_report.R
Labels: Low risk

#702 Change the logic used to decide whether bioenergy demand and ghg prices are read from a REMIND report
  CHANGELOG.md
  scripts/start_functions.R
Labels: Low risk

#703 bugfix start_functions.R and 80_optimization
  CHANGELOG.md
  modules/80_optimization/nlp_apr17/solve.gms
  scripts/start_functions.R
Labels: Minor, bugfix

#704 Fader for GHG pricing policy
  CHANGELOG.md
  config/default.cfg
  modules/56_ghg_policy/price_aug22/declarations.gms
  modules/56_ghg_policy/price_aug22/input.gms
  modules/56_ghg_policy/price_aug22/preloop.gms
Labels: enhancement, Low risk

#698 revision of SCP implementation for milk and meat alternatives
  CHANGELOG.md
  config/default.cfg
  literature.bib
  modules/15_food/anthro_iso_jun22/declarations.gms
  modules/15_food/anthro_iso_jun22/exodietmacro.gms
  modules/15_food/anthro_iso_jun22/input.gms
  modules/15_food/anthropometrics_jan18/declarations.gms
  modules/15_food/anthropometrics_jan18/input.gms
  modules/15_food/anthropometrics_jan18/intersolve.gms
  modules/15_food/anthropometrics_jan18/presolve.gms
Labels: enhancement, Medium risk

#705 Small script update and parameter fix
  CHANGELOG.md
  modules/15_food/anthro_iso_jun22/declarations.gms
  modules/15_food/anthropometrics_jan18/declarations.gms
  scripts/start/projects/project_EAT2p0.R
  scripts/start/projects/project_EAT2p0_DeepDive.R
Labels: Minor, Low risk, bugfix
