Repository magpiemodel/magpie, pull requests merged in 2024-03, with the labels that each got.

#637 Improved cropland relocation in response to SNV policy & sm_fix_cc correction
  CHANGELOG.md
  config/default.cfg
  core/macros.gms
  core/sets.gms
  literature.bib
  main.gms
  modules/22_land_conservation/area_based_apr22/preloop.gms
  modules/30_crop/endo_apr21/declarations.gms
  modules/30_crop/endo_apr21/equations.gms
  modules/30_crop/endo_apr21/input.gms
  modules/30_crop/endo_apr21/input/files
  modules/30_crop/endo_apr21/postsolve.gms
  modules/30_crop/endo_apr21/preloop.gms
  modules/30_crop/endo_apr21/presolve.gms
  modules/30_crop/endo_apr21/sets.gms
  modules/30_crop/penalty_apr22/declarations.gms
  modules/30_crop/penalty_apr22/equations.gms
  modules/30_crop/penalty_apr22/input.gms
  modules/30_crop/penalty_apr22/input/files
  modules/30_crop/penalty_apr22/postsolve.gms
  modules/30_crop/penalty_apr22/preloop.gms
  modules/30_crop/penalty_apr22/presolve.gms
  modules/30_crop/rotation_apr22/declarations.gms
  modules/30_crop/rotation_apr22/equations.gms
  modules/30_crop/rotation_apr22/input.gms
  modules/30_crop/rotation_apr22/input/files
  modules/30_crop/rotation_apr22/postsolve.gms
  modules/30_crop/rotation_apr22/preloop.gms
  modules/30_crop/rotation_apr22/presolve.gms
  modules/35_natveg/dynamic_feb21/preloop.gms
  modules/42_water_demand/agr_sector_aug13/preloop.gms
  modules/42_water_demand/all_sectors_aug13/preloop.gms
  modules/44_biodiversity/bv_btc_mar21/preloop.gms
  modules/52_carbon/normal_dec17/input.gms
Labels: enhancement, Medium risk

#643 update of livestock factor requirements
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  config/scenario_fsec.csv
  modules/30_crop/penalty_apr22/sets.gms
  modules/30_crop/rotation_apr22/sets.gms
  modules/70_livestock/fbask_jan16/declarations.gms
  modules/70_livestock/fbask_jan16/equations.gms
  modules/70_livestock/fbask_jan16/input.gms
  modules/70_livestock/fbask_jan16/input/files
  modules/70_livestock/fbask_jan16/preloop.gms
Labels: Medium risk, bugfix

#636 Updated FSEC and EAT Lancet 2.0 start scripts
  CHANGELOG.md
  config/default.cfg
  config/scenario_fsec.csv
  modules/58_peatland/v2/equations.gms
  modules/59_som/cellpool_aug16/postsolve.gms
  modules/59_som/cellpool_aug16/presolve.gms
  modules/59_som/cellpool_jan23/postsolve.gms
  modules/59_som/cellpool_jan23/presolve.gms
  scripts/output/projects/FSDP_collect.R
  scripts/output/projects/agmip_report.R
  scripts/output/projects/eat2p0_report.R
  scripts/projects/fsec.R
  scripts/start/extra/recalibrate_FSEC.R
  scripts/start/projects/project_EAT2p0.R
  scripts/start/projects/project_FSEC_Scenarios.R
Labels: Minor, Low risk

#645 Bugfix Trade Timber Products
  CHANGELOG.md
  config/default.cfg
  modules/15_food/anthro_iso_jun22/input.gms
  modules/15_food/anthropometrics_jan18/input.gms
  modules/21_trade/selfsuff_reduced/declarations.gms
  modules/21_trade/selfsuff_reduced/equations.gms
  modules/21_trade/selfsuff_reduced/input.gms
  modules/21_trade/selfsuff_reduced/postsolve.gms
  modules/21_trade/selfsuff_reduced/preloop.gms
  modules/21_trade/selfsuff_reduced/realization.gms
  modules/21_trade/selfsuff_reduced/scaling.gms
  modules/21_trade/selfsuff_reduced_bilateral22/declarations.gms
  modules/21_trade/selfsuff_reduced_bilateral22/equations.gms
  modules/21_trade/selfsuff_reduced_bilateral22/input.gms
  modules/21_trade/selfsuff_reduced_bilateral22/postsolve.gms
  modules/21_trade/selfsuff_reduced_bilateral22/preloop.gms
  modules/21_trade/selfsuff_reduced_bilateral22/scaling.gms
  modules/32_forestry/dynamic_feb21/input.gms
  modules/56_ghg_policy/price_aug22/input.gms
  modules/58_peatland/v2/presolve.gms
  scripts/output/projects/FSDP_collect.R
  scripts/projects/fsec.R
Labels: High risk

#647 Changed BII reporting in FSDP collect + minor addition in SEALS reporting script
  CHANGELOG.md
  scripts/output/extra/reportMAgPIE2SEALS.R
  scripts/output/projects/FSDP_collect.R
Labels: Low risk
