Repository magpiemodel/magpie, pull requests merged in 2024-04, with the labels that each got.

#656 Update PB scripts and bugfix in new EATLancet diet
  CHANGELOG.md
  config/scenario_config.csv
  modules/15_food/anthro_iso_jun22/exodietmacro.gms
  scripts/output/projects/FSDP_collect.R
  scripts/output/projects/FSDP_collect2.R
  scripts/projects/fsec.R
  scripts/start/projects/project_EAT2p0.R
  scripts/start/projects/project_EAT2p0_DeepDive.R
Labels: Low risk, bugfix

#659 bugfix 34_urban static
  CHANGELOG.md
  modules/34_urban/static/presolve.gms
Labels: Low risk, bugfix

#664 bugfixes develop
  CHANGELOG.md
  config/scenario_config.csv
  config/scenario_fsec.csv
  modules/44_biodiversity/bii_target/equations.gms
  modules/44_biodiversity/bii_target/preloop.gms
  scripts/output/extra/disaggregation.R
  scripts/projects/fsec.R
Labels: Minor, Low risk, bugfix

#669 remove deprecated scripts + spam related code
  CHANGELOG.md
  scripts/insertheader/insertheader.R
  scripts/output/deprecated/disaggregation_cropsplit.R
  scripts/output/deprecated/disaggregation_transitions.R
  scripts/start_functions.R
Labels: Minor, Low risk
