Repository magpiemodel/magpie, pull requests merged in 2024-09, with the labels that each got.

#700 Clean up scenario configs
  CHANGELOG.md
  config/default.cfg
  config/projects/scenario_config_el2.csv
  config/projects/scenario_config_frst_shock.csv
  config/projects/scenario_config_fsec.csv
  config/projects/scenario_config_gcs.csv
  config/projects/scenario_config_genie.csv
  config/projects/scenario_config_lama.csv
  config/projects/scenario_config_navigate.csv
  config/projects/scenario_config_ngfs.csv
  config/scenario_config.csv
  scripts/projects/fsec.R
  scripts/start/projects/GENIE_0_default.R
  scripts/start/projects/GENIE_2_bm-priced.R
  scripts/start/projects/GENIE_3_bm-demand.R
  scripts/start/projects/GENIE_4_feedback.R
  scripts/start/projects/project_EAT2p0.R
  scripts/start/projects/project_EAT2p0_DeepDive.R
  scripts/start/projects/project_GCS.R
  scripts/start/projects/project_LAMACLIMA_WP4.R
Labels: Low risk

#714 Update 58_peatland and 80_optimization modules
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  core/macros.gms
  modules/15_food/anthro_iso_jun22/intersolve.gms
  modules/15_food/anthro_iso_jun22/presolve.gms
  modules/15_food/anthropometrics_jan18/intersolve.gms
  modules/15_food/anthropometrics_jan18/presolve.gms
  modules/29_cropland/detail_apr24/input.gms
  modules/29_cropland/detail_apr24/preloop.gms
  modules/32_forestry/dynamic_may24/declarations.gms
  modules/32_forestry/dynamic_may24/equations.gms
  modules/32_forestry/dynamic_may24/postsolve.gms
  modules/35_natveg/pot_forest_may24/presolve.gms
  modules/58_peatland/v2/declarations.gms
  modules/58_peatland/v2/equations.gms
  modules/58_peatland/v2/input.gms
  modules/58_peatland/v2/postsolve.gms
  modules/58_peatland/v2/presolve.gms
  modules/58_peatland/v2/realization.gms
  modules/80_optimization/lp_nlp_apr17/solve.gms
  modules/80_optimization/nlp_apr17/solve.gms
  modules/80_optimization/nlp_par/solve.gms
  scripts/output/extra/convertValidation.R
  scripts/slurmStart.yml
  scripts/start/projects/paper_peatlandTax.R
  scripts/start/projects/project_ABCDR.R
Labels: Minor, High risk, bugfix

#719 Update ABCDR
  CHANGELOG.md
  config/default.cfg
  modules/29_cropland/detail_apr24/input.gms
  modules/29_cropland/detail_apr24/preloop.gms
  scripts/start/projects/project_ABCDR.R
Labels: Low risk

#715 cleaned up EL2 AgMIP start script
  scripts/start/projects/project_EAT2p0.R
Labels: Low risk

#718 Added convertToNetCDF output script
  CHANGELOG.md
  scripts/output/extra/convertToNetCDF.R
Labels: enhancement, Low risk

#723 Shift to sticky as default realization in the 38_factor_costs module
  CHANGELOG.md
  config/default.cfg
Labels: High risk

#721 Start script 'healthy landscapes paper' and output script for automatic submission of SEALS runs
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  config/projects/scenario_config_year_fix.csv
  scripts/output/extra/disaggregation.R
  scripts/output/extra/highres.R
  scripts/output/extra/runSEALSallocation.R
  scripts/projects/fsec.R
  scripts/run_submit/submit_priority.sh
  scripts/run_submit/submit_priority_highMem.sh
  scripts/run_submit/submit_short.sh
  scripts/run_submit/submit_short_highMem.sh
  scripts/run_submit/submit_standby.sh
  scripts/run_submit/submit_standby_dayMax.sh
  scripts/run_submit/submit_standby_highMem.sh
  scripts/run_submit/submit_standby_highMem_dayMax.sh
  scripts/slurmOutput.yml
  scripts/start/projects/GENIE_0_default.R
  scripts/start/projects/GENIE_1_tau-export.R
  scripts/start/projects/GENIE_2_bm-priced.R
  scripts/start/projects/GENIE_3_bm-demand.R
  scripts/start/projects/GENIE_4_feedback.R
  scripts/start/projects/paper_healthyLscps.R
  scripts/start/projects/paper_peatlandTax.R
  scripts/start/projects/project_ABCDR.R
  scripts/start/projects/project_EAT2p0.R
  scripts/start/projects/project_EAT2p0_DeepDive.R
  scripts/start/projects/project_LAMACLIMA_WP4.R
Labels: Low risk

#727 Bugfix in water cost equation
  CHANGELOG.md
  main.gms
  modules/11_costs/default/equations.gms
Labels: Minor, Low risk, bugfix
