Repository magpiemodel/magpie, pull requests merged in 2024-06, with the labels that each got.

#668 modified agmip output script to use piaminterfaces
  CHANGELOG.md
  scripts/output/projects/agmip_merge_report.R
Labels: Low risk

#682 bugfix negative values in p35_forest_recovery_area
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  config/scenario_fsec.csv
  modules/09_drivers/aug17/declarations.gms
  modules/09_drivers/aug17/input.gms
  modules/10_land/landmatrix_dec18/presolve.gms
  modules/21_trade/selfsuff_reduced_bilateral22/input.gms
  modules/22_land_conservation/area_based_apr22/input.gms
  modules/30_crop/endo_apr21/input.gms
  modules/30_crop/penalty_apr22/input.gms
  modules/30_crop/rotation_apr22/input.gms
  modules/32_forestry/dynamic_may24/presolve.gms
  modules/35_natveg/pot_forest_may24/declarations.gms
  modules/35_natveg/pot_forest_may24/equations.gms
  modules/35_natveg/pot_forest_may24/input.gms
  modules/35_natveg/pot_forest_may24/postsolve.gms
  modules/35_natveg/pot_forest_may24/preloop.gms
  modules/35_natveg/pot_forest_may24/presolve.gms
  modules/35_natveg/pot_forest_may24/realization.gms
  modules/38_factor_costs/sticky_labor/input.gms
  modules/42_water_demand/agr_sector_aug13/input.gms
  modules/42_water_demand/all_sectors_aug13/input.gms
  modules/42_water_demand/all_sectors_aug13/presolve.gms
  modules/73_timber/default/preloop.gms
  scripts/start/test_runs.R
Labels: Minor, bugfix

#685 Bugfix warning disaggregation
  scripts/output/extra/disaggregation.R
Labels: Minor, Low risk, bugfix

#687 Adjust slurm job handling
  CHANGELOG.md
  output.R
  scripts/helper.R
  scripts/run_submit/submit_medium.sh
  scripts/run_submit/submit_priority.sh
  scripts/run_submit/submit_priority_maxMem.sh
  scripts/run_submit/submit_short.sh
  scripts/run_submit/submit_short_maxMem.sh
  scripts/run_submit/submit_standby.sh
  scripts/run_submit/submit_standby_dayMax.sh
  scripts/run_submit/submit_standby_maxMem.sh
  scripts/run_submit/submit_standby_maxMem_dayMax.sh
  scripts/slurmOutput.yml
  scripts/slurmStart.yml
  scripts/start_functions.R
  start.R
Labels: Medium risk

#688 turn renv::snapshot error into warning
  output.R
Labels: Low risk

#689 Added entire-year non-ag water demand for PB postprocessing
  CHANGELOG.md
  main.gms
  modules/42_water_demand/agr_sector_aug13/declarations.gms
  modules/42_water_demand/agr_sector_aug13/presolve.gms
  modules/42_water_demand/agr_sector_aug13/sets.gms
  modules/42_water_demand/all_sectors_aug13/declarations.gms
  modules/42_water_demand/all_sectors_aug13/input.gms
  modules/42_water_demand/all_sectors_aug13/presolve.gms
  modules/42_water_demand/input/files
  modules/44_biodiversity/bv_btc_mar21/not_used.txt
  scripts/output/extra/checkSummation.R
  scripts/start/projects/project_EAT2p0.R
  scripts/start/projects/project_EAT2p0_DeepDive.R
Labels: Low risk

#680 add output report to validate spatial patterns in EU countries
  CHANGELOG.md
  scripts/output/projects/EU_report.R
  scripts/output/projects/EU_report.Rmd
Labels: enhancement, Low risk

#678 add "fbask_jan16_sticky" realization to livestock module
  CHANGELOG.md
  CITATION.cff
  config/default.cfg
  modules/70_livestock/fbask_jan16/not_used.txt
  modules/70_livestock/fbask_jan16_sticky/declarations.gms
  modules/70_livestock/fbask_jan16_sticky/equations.gms
  modules/70_livestock/fbask_jan16_sticky/input.gms
  modules/70_livestock/fbask_jan16_sticky/input/files
  modules/70_livestock/fbask_jan16_sticky/postsolve.gms
  modules/70_livestock/fbask_jan16_sticky/preloop.gms
  modules/70_livestock/fbask_jan16_sticky/presolve.gms
  modules/70_livestock/fbask_jan16_sticky/realization.gms
  modules/70_livestock/fbask_jan16_sticky/sets.gms
  modules/70_livestock/module.gms
Labels: enhancement, Medium risk

#693 bugfix in start.R and output.R
  CHANGELOG.md
  output.R
  start.R
Labels: Low risk, bugfix

#677 Refactor selfsuff reduced module
  CHANGELOG.md
  core/macros.gms
  modules/21_trade/selfsuff_reduced/equations.gms
  modules/21_trade/selfsuff_reduced/realization.gms
Labels: enhancement, Suggestion, Medium risk
