Repository magpiemodel/magpie, pull requests merged in 2024-05, with the labels that each got.

#675 update 80_optimization
  CHANGELOG.md
  config/default.cfg
  modules/60_bioenergy/1st2ndgen_priced_feb24/sets.gms
  modules/80_optimization/lp_nlp_apr17/input.gms
  modules/80_optimization/lp_nlp_apr17/solve.gms
  modules/80_optimization/nlp_apr17/declarations.gms
  modules/80_optimization/nlp_apr17/input.gms
  modules/80_optimization/nlp_apr17/solve.gms
  modules/80_optimization/nlp_par/declarations.gms
  modules/80_optimization/nlp_par/input.gms
  modules/80_optimization/nlp_par/solve.gms
  scripts/start/test_runs.R
Labels: bugfix

#674 New fader implementation in modules 15_food and 70_livestock
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  main.gms
  modules/15_food/anthro_iso_jun22/declarations.gms
  modules/15_food/anthro_iso_jun22/exodietmacro.gms
  modules/15_food/anthro_iso_jun22/input.gms
  modules/15_food/anthro_iso_jun22/preloop.gms
  modules/15_food/anthro_iso_jun22/sets.gms
  modules/15_food/anthropometrics_jan18/declarations.gms
  modules/15_food/anthropometrics_jan18/input.gms
  modules/15_food/anthropometrics_jan18/intersolve.gms
  modules/15_food/anthropometrics_jan18/preloop.gms
  modules/15_food/anthropometrics_jan18/presolve.gms
  modules/15_food/anthropometrics_jan18/sets.gms
  modules/15_food/input/files
  modules/70_livestock/fbask_jan16/declarations.gms
  modules/70_livestock/fbask_jan16/input.gms
  modules/70_livestock/fbask_jan16/input/files
  modules/70_livestock/fbask_jan16/preloop.gms
  scripts/start/projects/paper_scp.R
  scripts/start/projects/project_agmip.R
Labels: enhancement, Minor, Medium risk

#662 Added options for baseline protection
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  config/scenario_fsec.csv
  modules/22_land_conservation/area_based_apr22/declarations.gms
  modules/22_land_conservation/area_based_apr22/input.gms
  modules/22_land_conservation/area_based_apr22/preloop.gms
  modules/22_land_conservation/area_based_apr22/presolve.gms
  modules/22_land_conservation/area_based_apr22/sets.gms
  scripts/output/extra/disaggregation.R
Labels: Medium risk

#649 added summation check
  CHANGELOG.md
  CITATION.cff
  scripts/output/extra/checkSummation.R
Labels: Minor, Low risk

#679 Fix division by zero in yield calibration
  CHANGELOG.md
  modules/14_yields/managementcalib_aug19/preloop.gms
Labels: Low risk, bugfix

#676 New forest recovery based on potential forest area
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  config/scenario_fsec.csv
  core/macros.gms
  core/sets.gms
  main.gms
  modules/14_yields/managementcalib_aug19/declarations.gms
  modules/14_yields/managementcalib_aug19/input.gms
  modules/14_yields/managementcalib_aug19/preloop.gms
  modules/14_yields/managementcalib_aug19/presolve.gms
  modules/22_land_conservation/area_based_apr22/presolve.gms
  modules/32_forestry/dynamic_may24/equations.gms
  modules/32_forestry/dynamic_may24/preloop.gms
  modules/32_forestry/dynamic_may24/presolve.gms
  modules/35_natveg/dynamic_feb21/declarations.gms
  modules/35_natveg/input/files
  modules/35_natveg/module.gms
  modules/35_natveg/pot_forest_may24/declarations.gms
  modules/35_natveg/pot_forest_may24/equations.gms
  modules/35_natveg/pot_forest_may24/input.gms
  modules/35_natveg/pot_forest_may24/postsolve.gms
  modules/35_natveg/pot_forest_may24/preloop.gms
  modules/35_natveg/pot_forest_may24/presolve.gms
  modules/35_natveg/pot_forest_may24/realization.gms
  modules/35_natveg/pot_forest_may24/scaling.gms
  modules/35_natveg/pot_forest_may24/sets.gms
  modules/52_carbon/normal_dec17/declarations.gms
  modules/52_carbon/normal_dec17/input.gms
  modules/52_carbon/normal_dec17/start.gms
  modules/59_som/cellpool_aug16/equations.gms
  modules/59_som/cellpool_aug16/not_used.txt
  modules/59_som/cellpool_jan23/equations.gms
  modules/59_som/cellpool_jan23/not_used.txt
  modules/59_som/static_jan19/declarations.gms
  modules/59_som/static_jan19/equations.gms
  modules/59_som/static_jan19/postsolve.gms
  modules/59_som/static_jan19/sets.gms
  modules/80_optimization/nlp_apr17/solve.gms
Labels: enhancement, Major, High risk, data update

#672 Updated AEI initialization to Mehta (2024)
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  literature.bib
  modules/37_labor_prod/exo/sets.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/realization.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/sets.gms
  modules/41_area_equipped_for_irrigation/static/realization.gms
  modules/41_area_equipped_for_irrigation/static/sets.gms
  modules/42_water_demand/agr_sector_aug13/realization.gms
  scripts/output/projects/FSEC_water.R
  scripts/output/projects/inms_reporting_reg.R
  scripts/start/projects/project_EAT2p0.R
  scripts/start/projects/project_EAT2p0_DeepDive.R
Labels: Minor, Low risk, data update

#681 bugfix 35_natveg forest recovery
  modules/35_natveg/pot_forest_may24/presolve.gms
Labels: Low risk, bugfix
