Repository magpiemodel/magpie, pull requests merged in 2024-11, with the labels that each got.

#740 hotfix for rds_report.R output script: fix units in "report.rds" file
  scripts/output/rds_report.R
  scripts/output/rds_report_iso.R
Labels: Low risk, bugfix

#744 bugfixes for more robust feasibility
  CHANGELOG.md
  modules/10_land/landmatrix_dec18/declarations.gms
  modules/10_land/landmatrix_dec18/equations.gms
  modules/10_land/landmatrix_dec18/postsolve.gms
  modules/10_land/landmatrix_dec18/scaling.gms
  modules/20_processing/substitution_may21/scaling.gms
  modules/38_factor_costs/sticky_labor/scaling.gms
  modules/44_biodiversity/bii_target/equations.gms
  modules/44_biodiversity/bii_target/presolve.gms
  modules/44_biodiversity/bii_target_apr24/equations.gms
  modules/44_biodiversity/bii_target_apr24/preloop.gms
  modules/44_biodiversity/bii_target_apr24/presolve.gms
  modules/70_livestock/fbask_jan16/realization.gms
  modules/70_livestock/fbask_jan16/scaling.gms
  modules/70_livestock/fbask_jan16_sticky/realization.gms
  modules/70_livestock/fbask_jan16_sticky/scaling.gms
  modules/71_disagg_lvst/foragebased_aug18/realization.gms
  modules/71_disagg_lvst/foragebased_jul23/realization.gms
  modules/71_disagg_lvst/foragebased_jul23/scaling.gms
  scripts/projects/fsec.R
  scripts/start/projects/paper_peatlandTax.R
  scripts/start/projects/project_ABCDR.R
Labels: enhancement, bugfix

#738 Peatland considered during disaggregation
  CHANGELOG.md
  main.gms
  scripts/output/extra/disaggregation.R
Labels: Low risk

#745 follow-up fix for PR744
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  config/projects/scenario_config_el2.csv
  config/projects/scenario_config_fsec.csv
  config/scenario_config.csv
  main.gms
  modules/10_land/landmatrix_dec18/declarations.gms
  modules/10_land/landmatrix_dec18/equations.gms
  modules/10_land/landmatrix_dec18/input.gms
  modules/10_land/landmatrix_dec18/postsolve.gms
  modules/10_land/landmatrix_dec18/realization.gms
  modules/10_land/landmatrix_dec18/scaling.gms
  modules/20_processing/substitution_may21/scaling.gms
  modules/29_cropland/detail_apr24/preloop.gms
  modules/29_cropland/detail_apr24/presolve.gms
  modules/30_croparea/detail_apr24/preloop.gms
  modules/30_croparea/simple_apr24/preloop.gms
  modules/31_past/endo_jun13/not_used.txt
  modules/31_past/endo_jun13/preloop.gms
  modules/31_past/endo_jun13/realization.gms
  modules/31_past/grasslands_apr22/not_used.txt
  modules/31_past/grasslands_apr22/preloop.gms
  modules/32_forestry/dynamic_may24/preloop.gms
  modules/32_forestry/dynamic_may24/presolve.gms
  modules/32_forestry/dynamic_may24/scaling.gms
  modules/34_urban/exo_nov21/preloop.gms
  modules/34_urban/exo_nov21/scaling.gms
  modules/34_urban/static/presolve.gms
  modules/35_natveg/pot_forest_may24/preloop.gms
  modules/35_natveg/pot_forest_may24/presolve.gms
  modules/44_biodiversity/bii_target/declarations.gms
  modules/44_biodiversity/bii_target/equations.gms
  modules/44_biodiversity/bii_target/input.gms
  modules/44_biodiversity/bii_target/preloop.gms
  modules/44_biodiversity/bii_target/presolve.gms
  modules/44_biodiversity/bii_target/sets.gms
  modules/44_biodiversity/bii_target_apr24/declarations.gms
  modules/44_biodiversity/bii_target_apr24/equations.gms
  modules/44_biodiversity/bii_target_apr24/input.gms
  modules/44_biodiversity/bii_target_apr24/preloop.gms
  modules/44_biodiversity/bii_target_apr24/presolve.gms
  modules/44_biodiversity/bii_target_apr24/sets.gms
  modules/58_peatland/v2/realization.gms
  modules/58_peatland/v2/scaling.gms
  modules/73_timber/default/scaling.gms
  scripts/start/extra/recalibrateH16.R
  scripts/start/projects/paper_peatlandTax.R
  scripts/start/projects/project_ABCDR.R
  scripts/start/projects/project_EAT2p0.R
Labels: High risk, bugfix

#747 bugfix 1st gen bioenergy subsidy
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  config/projects/scenario_config_fsec.csv
  main.gms
  modules/60_bioenergy/1st2ndgen_priced_feb24/input.gms
  modules/60_bioenergy/1stgen_priced_dec18/input.gms
  scripts/start/projects/paper_peatlandTax.R
Labels: Minor, Low risk, bugfix

#748 mrdowscale scripts
  CHANGELOG.md
  DESCRIPTION
  scripts/output/extra/mrdownscale.R
  scripts/output/extra/mrdownscale_LUH2.R
Labels: Low risk

#749 option for NPI NDC reversal
  CHANGELOG.md
  config/default.cfg
  modules/32_forestry/dynamic_may24/declarations.gms
  modules/32_forestry/dynamic_may24/equations.gms
  modules/32_forestry/dynamic_may24/input.gms
  modules/32_forestry/dynamic_may24/preloop.gms
  modules/32_forestry/dynamic_may24/presolve.gms
  modules/35_natveg/pot_forest_may24/input.gms
  modules/35_natveg/pot_forest_may24/presolve.gms
Labels: enhancement, Low risk

#752 bugfix npi_ndc_reversal
  modules/32_forestry/dynamic_may24/presolve.gms
Labels: Minor, bugfix

#751 removed grasslands realization
  CHANGELOG.md
  config/default.cfg
  config/scenario_config.csv
  modules/31_past/grasslands_apr22/declarations.gms
  modules/31_past/grasslands_apr22/equations.gms
  modules/31_past/grasslands_apr22/input.gms
  modules/31_past/grasslands_apr22/not_used.txt
  modules/31_past/grasslands_apr22/postsolve.gms
  modules/31_past/grasslands_apr22/preloop.gms
  modules/31_past/grasslands_apr22/presolve.gms
  modules/31_past/grasslands_apr22/realization.gms
  modules/31_past/grasslands_apr22/sets.gms
  modules/31_past/input/files
  modules/31_past/module.gms
  scripts/start/projects/paper_grassland.R
Labels: Low risk

#753 bugfix remove empty files file
  modules/31_past/input/files
Labels: Minor, bugfix

#754 bugfix removal grassland realisation
  CHANGELOG.md
  modules/13_tc/endo_jan22/input.gms
  modules/13_tc/endo_jan22/preloop.gms
  modules/13_tc/endo_jan22/presolve.gms
  modules/13_tc/exo/input.gms
  modules/13_tc/exo/preloop.gms
  modules/31_past/endo_jun13/not_used.txt
  modules/31_past/static/not_used.txt
Labels: Minor, bugfix

#750 option for exogenous peatland rewetting
  CHANGELOG.md
  config/default.cfg
  modules/58_peatland/input/files
  modules/58_peatland/v2/declarations.gms
  modules/58_peatland/v2/equations.gms
  modules/58_peatland/v2/input.gms
  modules/58_peatland/v2/postsolve.gms
  modules/58_peatland/v2/preloop.gms
  modules/58_peatland/v2/presolve.gms
  modules/58_peatland/v2/sets.gms
  scripts/start/projects/paper_peatlandTax.R
Labels: enhancement, Low risk
