Repository magpiemodel/magpie, pull requests merged in 2025-03, with the labels that each got.

#781 Bugfix forestry prices and trade cost
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  core/macros.gms
  modules/21_trade/selfsuff_reduced/input.gms
  modules/21_trade/selfsuff_reduced_bilateral22/input.gms
  modules/32_forestry/dynamic_may24/input.gms
  modules/32_forestry/dynamic_may24/presolve.gms
  scripts/start/projects/project_ScenarioMIP.R
Labels: Medium risk, bugfix

#783 fix typo in 09_drivers/aug17/input.gms
  modules/09_drivers/aug17/input.gms
Labels: Low risk

#784 Improve LUC CO2 emission dynamics
  CHANGELOG.md
  config/default.cfg
  modules/35_natveg/pot_forest_may24/input.gms
  modules/56_ghg_policy/price_aug22/input.gms
  modules/56_ghg_policy/price_aug22/preloop.gms
  modules/58_peatland/v2/declarations.gms
  modules/58_peatland/v2/equations.gms
  modules/58_peatland/v2/input.gms
  modules/58_peatland/v2/postsolve.gms
  scripts/start/projects/project_ScenarioMIP.R
Labels: enhancement, Minor, High risk

#774 Introduce simple soil carbon management (scm) option
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  config/scenario_config.csv
  literature.bib
  main.gms
  modules/11_costs/default/equations.gms
  modules/59_som/cellpool_aug16/declarations.gms
  modules/59_som/cellpool_aug16/equations.gms
  modules/59_som/cellpool_aug16/input.gms
  modules/59_som/cellpool_aug16/input/files
  modules/59_som/cellpool_aug16/not_used.txt
  modules/59_som/cellpool_aug16/postsolve.gms
  modules/59_som/cellpool_aug16/preloop.gms
  modules/59_som/cellpool_aug16/presolve.gms
  modules/59_som/cellpool_aug16/realization.gms
  modules/59_som/cellpool_aug16/scaling.gms
  modules/59_som/cellpool_aug16/sets.gms
  modules/59_som/cellpool_jan23/declarations.gms
  modules/59_som/cellpool_jan23/equations.gms
  modules/59_som/cellpool_jan23/input.gms
  modules/59_som/cellpool_jan23/postsolve.gms
  modules/59_som/cellpool_jan23/preloop.gms
  modules/59_som/cellpool_jan23/presolve.gms
  modules/59_som/cellpool_jan23/realization.gms
  modules/59_som/module.gms
  modules/59_som/static_jan19/declarations.gms
  modules/59_som/static_jan19/not_used.txt
  modules/59_som/static_jan19/postsolve.gms
  modules/59_som/static_jan19/presolve.gms
  renv/activate.R
  scripts/start/projects/project_ScenarioMIP.R
Labels: enhancement, High risk, Medium risk

#785 Bugfix cellpool_aug16 -> cellpool_jan23
  config/projects/scenario_config_fsec.csv
  config/scenario_config.csv
  modules/59_som/cellpool_jan23/preloop.gms
  scripts/start/projects/project_inms2.R
  scripts/start/projects/project_sim4nexus.R
  scripts/start/projects/test_rotations.R
Labels: Minor, Low risk, bugfix

#787 update rev4.117 + disaggregation output scripts
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  config/projects/scenario_config_el2.csv
  config/projects/scenario_config_fsec.csv
  config/scenario_config.csv
  main.gms
  modules/09_drivers/aug17/sets.gms
  modules/56_ghg_policy/price_aug22/preloop.gms
  modules/58_peatland/v2/preloop.gms
  renv/activate.R
  scripts/output/extra/disaggregation.R
  scripts/output/extra/disaggregation_LUH2.R
  scripts/start/extra/recalibrateH16.R
  scripts/start/projects/paper_peatlandTax.R
  scripts/start/projects/project_ABCDR.R
  scripts/start/projects/project_EAT2p0.R
  scripts/start/projects/project_ScenarioMIP.R
  scripts/start/projects/project_WetHorizons.R
Labels: Medium risk, bugfix

#790 Annual upper limit for re/afforestation + update start script ScenarioMIP
  CHANGELOG.md
  config/default.cfg
  modules/32_forestry/dynamic_may24/declarations.gms
  modules/32_forestry/dynamic_may24/equations.gms
  modules/32_forestry/dynamic_may24/input.gms
  modules/32_forestry/dynamic_may24/postsolve.gms
  modules/32_forestry/dynamic_may24/presolve.gms
  modules/58_peatland/v2/input.gms
  scripts/start/projects/project_ScenarioMIP.R
Labels: Minor, High risk

#789 simplifying equation (its the same equation, just written differently…
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  main.gms
  modules/15_food/anthro_iso_jun22/declarations.gms
  modules/15_food/anthro_iso_jun22/exodietmacro.gms
  modules/15_food/anthro_iso_jun22/input.gms
  modules/15_food/anthro_iso_jun22/preloop.gms
  modules/38_factor_costs/sticky_feb18/equations.gms
  modules/38_factor_costs/sticky_labor/equations.gms
  modules/38_factor_costs/sticky_labor/preloop.gms
  modules/41_area_equipped_for_irrigation/endo_apr13/equations.gms
  renv/activate.R
  scripts/start/projects/project_ScenarioMIP.R
Labels: Minor, Medium risk
