Repository magpiemodel/magpie, pull requests merged in 2025-02, with the labels that each got.

#772 Update land conversion cost calibration for cropland - FAO as target data set
  CHANGELOG.md
  DESCRIPTION
  README.md
  config/default.cfg
  config/projects/scenario_config_fsec.csv
  main.gms
  scripts/calibration/landconversion_cost.R
  scripts/start/extra/recalibrateH16.R
  scripts/start/extra/recalibrate_FSEC.R
  scripts/start/extra/recalibrate_default.R
  scripts/start/projects/project_ABCDR.R
  scripts/start_functions.R
Labels: Minor, High risk

#767 Elastic Food Demand and Tax recycling
  CHANGELOG.md
  config/default.cfg
  main.gms
  modules/15_food/anthro_iso_jun22/declarations.gms
  modules/15_food/anthro_iso_jun22/equations.gms
  modules/15_food/anthro_iso_jun22/input.gms
  modules/15_food/anthro_iso_jun22/intersolve.gms
  modules/15_food/anthro_iso_jun22/preloop.gms
  modules/15_food/anthro_iso_jun22/presolve.gms
  modules/15_food/anthro_iso_jun22/sets.gms
  modules/15_food/anthropometrics_jan18/declarations.gms
  modules/15_food/anthropometrics_jan18/equations.gms
  modules/15_food/anthropometrics_jan18/hierarchical_tree.png
  modules/15_food/anthropometrics_jan18/input.gms
  modules/15_food/anthropometrics_jan18/intersolve.gms
  modules/15_food/anthropometrics_jan18/postsolve.gms
  modules/15_food/anthropometrics_jan18/preloop.gms
  modules/15_food/anthropometrics_jan18/presolve.gms
  modules/15_food/anthropometrics_jan18/realization.gms
  modules/15_food/anthropometrics_jan18/scaling.gms
  modules/15_food/anthropometrics_jan18/sets.gms
  modules/16_demand/sector_may15/input.gms
  renv/settings.dcf
  scripts/start/projects/test_elastic_demand.R
Labels: Medium risk, bugfix

#775 Simplify 60_bioenergy and change default realization
  CHANGELOG.md
  config/default.cfg
  modules/15_food/module.gms
  modules/60_bioenergy/1st2ndgen_priced_feb24/declarations.gms
  modules/60_bioenergy/1st2ndgen_priced_feb24/equations.gms
  modules/60_bioenergy/1st2ndgen_priced_feb24/input.gms
  modules/60_bioenergy/1st2ndgen_priced_feb24/preloop.gms
  modules/60_bioenergy/1st2ndgen_priced_feb24/presolve.gms
  modules/60_bioenergy/1stgen_priced_dec18/equations.gms
  modules/60_bioenergy/1stgen_priced_dec18/input.gms
  modules/60_bioenergy/module.gms
  scripts/start/projects/GENIE_1_tau-export.R
  scripts/start/projects/GENIE_2_bm-priced.R
  scripts/start/projects/GENIE_3_bm-demand.R
  scripts/start/projects/GENIE_4_feedback.R
Labels: High risk

#777 Revision timber demand and production + option for WDPA reversal
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  config/scenario_config.csv
  modules/22_land_conservation/area_based_apr22/input.gms
  modules/22_land_conservation/area_based_apr22/presolve.gms
  modules/32_forestry/dynamic_may24/declarations.gms
  modules/32_forestry/dynamic_may24/input.gms
  modules/32_forestry/dynamic_may24/preloop.gms
  modules/35_natveg/pot_forest_may24/equations.gms
  modules/35_natveg/pot_forest_may24/input.gms
  modules/35_natveg/pot_forest_may24/presolve.gms
  modules/73_timber/default/declarations.gms
  modules/73_timber/default/input.gms
  modules/73_timber/default/preloop.gms
  modules/73_timber/default/sets.gms
  scripts/start/projects/project_ScenarioMIP.R
Labels: enhancement, High risk

#779 updated start script
  CHANGELOG.md
  scripts/start/projects/project_EAT2p0.R
Labels: Low risk
