Repository magpiemodel/magpie, pull requests merged in 2025-06, with the labels that each got.

#811 optional temporal fader for start of C prive driven afforestation
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  config/scenario_config.csv
  modules/56_ghg_policy/price_aug22/declarations.gms
  modules/56_ghg_policy/price_aug22/equations.gms
  modules/56_ghg_policy/price_aug22/input.gms
  modules/56_ghg_policy/price_aug22/preloop.gms
  scripts/start/projects/project_ScenarioMIP.R
  scripts/start/projects/project_WetHorizons.R
Labels: Low risk

#802 Maccs steps fix
  CHANGELOG.md
  CITATION.cff
  core/sets.gms
Labels: Low risk, bugfix

#807 Add consumer margin to food price postsolve
  CHANGELOG.md
  config/default.cfg
  modules/15_food/anthro_iso_jun22/declarations.gms
  modules/15_food/anthro_iso_jun22/input.gms
  modules/15_food/anthro_iso_jun22/postsolve.gms
  modules/15_food/anthro_iso_jun22/preloop.gms
  modules/15_food/anthro_iso_jun22/sets.gms
  modules/15_food/input/files
Labels: Low risk

#812 Update input data from rev4.118 to rev rev4.119
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  config/projects/scenario_config_el2.csv
  config/projects/scenario_config_fsec.csv
  config/scenario_config.csv
  core/sets.gms
  main.gms
  modules/58_peatland/v2/input.gms
  renv/activate.R
  scripts/start/extra/recalibrateH16.R
  scripts/start/projects/project_ABCDR.R
  scripts/start/projects/project_EAT2p0.R
  scripts/start/projects/project_WetHorizons.R
Labels: Minor, High risk

#813 Update of pasture feed balance flows and inclusion of feed intake switch
  CHANGELOG.md
  DESCRIPTION
  config/default.cfg
  modules/53_methane/ipcc2006_aug22/equations.gms
  modules/53_methane/off/not_used.txt
  modules/55_awms/ipcc2006_aug16/equations.gms
  modules/55_awms/off/not_used.txt
  modules/70_livestock/fbask_jan16/declarations.gms
  modules/70_livestock/fbask_jan16/equations.gms
  modules/70_livestock/fbask_jan16/input.gms
  modules/70_livestock/fbask_jan16/postsolve.gms
  modules/70_livestock/fbask_jan16/preloop.gms
  modules/70_livestock/fbask_jan16/presolve.gms
  modules/70_livestock/fbask_jan16_sticky/declarations.gms
  modules/70_livestock/fbask_jan16_sticky/equations.gms
  modules/70_livestock/fbask_jan16_sticky/input.gms
  modules/70_livestock/fbask_jan16_sticky/postsolve.gms
  modules/70_livestock/fbask_jan16_sticky/preloop.gms
  modules/70_livestock/fbask_jan16_sticky/presolve.gms
  modules/71_disagg_lvst/foragebased_aug18/equations.gms
  modules/71_disagg_lvst/foragebased_aug18/not_used.txt
  modules/71_disagg_lvst/foragebased_jul23/equations.gms
  modules/71_disagg_lvst/off/not_used.txt
  modules/71_disagg_lvst/off/realization.gms
  modules/71_disagg_lvst/off/sets.gms
Labels: Minor, High risk

#814 mac/linux install instructions
  CHANGELOG.md
  Dockerfile
  README.md
Labels: Minor, Low risk
